# Limpieza de Movimientos

In [1]:
# CELDA 1 (Movimientos)
import pandas as pd
from pathlib import Path
import glob

carpeta = r'c:\Users\rdiezl\Desktop\proyecto\planificacion\Datos\Movimientos'
archivos = sorted(glob.glob(f'{carpeta}/*.xls') + glob.glob(f'{carpeta}/*.xlsx'))

dfs = []
for archivo in archivos:
    # La fila 2 tiene los nombres de columnas
    df = pd.read_excel(archivo, header=1, dtype={'Paleta': 'string'})

    # Limpiar Paleta (quitar solo el sufijo .0 si aparece)
    if 'Paleta' in df.columns:
        df['Paleta'] = (
            df['Paleta']
            .astype('string')
            .str.strip()
            .fillna('')
            .str.replace(r'\.0+$', '', regex=True)
        )

    # Quitar última fila (fila combinada/resumen)
    if len(df) > 0:
        df = df.iloc[:-1].copy()

    dfs.append(df)

movimientos = pd.concat(dfs, ignore_index=True)

print(f"Total de archivos leídos: {len(archivos)}")
print(f"Forma del dataframe: {movimientos.shape}")
movimientos.head()

Total de archivos leídos: 18
Forma del dataframe: (276044, 24)

,Tipo movimiento,Fecha inicio,Fecha finalización,Artículo,Denominación artículo,Pas. Ori.,Col. Ori.,Alt. Ori.,Pas. Des.,Col. Des.,...,Unidades / Caja,Unidades / Retráctil,V1,V2,VL,Propietario,Operario,Denominación operario,Lote fabricación,Código externo
0,CC,03/01/2022 08:24:57,03/01/2022 08:25:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,260.0,MANUEL GARRIDO,NaN,NaN
1,PI,03/01/2022 08:25:01,03/01/2022 08:31:38,022043,MESA BLANCA PATA MARRON TERRAZA MAHOU,015,87,20.0,NaN,302,...,1.0,NaN,0.0,0.0,0.0,34.0,260.0,MANUEL GARRIDO,NaN,NaN
2,PI,03/01/2022 08:31:38,03/01/2022 08:35:21,022043,MESA BLANCA PATA MARRON TERRAZA MAHOU,020,74,10.0,NaN,302,...,1.0,NaN,0.0,0.0,0.0,34.0,260.0,MANUEL GARRIDO,NaN,NaN
3,CC,03/01/2022 08:35:22,03/01/2022 08:35:23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,260.0,MANUEL GARRIDO,NaN,NaN
4,DC,03/01/2022 08:35:22,03/01/2022 08:35:22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,260.0,MANUEL GARRIDO,NaN,NaN

In [2]:
# CELDA 2 (Movimientos pedidos)
carpeta_pedidos = r'c:\Users\rdiezl\Desktop\proyecto\planificacion\Datos\Movimientos pedidos'
archivos_pedidos = sorted(glob.glob(f'{carpeta_pedidos}/*.xls') + glob.glob(f'{carpeta_pedidos}/*.xlsx'))

dfs_pedidos = []
for archivo in archivos_pedidos:
    # La fila 2 tiene los nombres de columnas
    df = pd.read_excel(archivo, header=1, dtype={'Paleta': 'string'})

    # Limpiar Paleta (quitar solo el sufijo .0 si aparece)
    if 'Paleta' in df.columns:
        df['Paleta'] = (
            df['Paleta']
            .astype('string')
            .str.strip()
            .fillna('')
            .str.replace(r'\.0+$', '', regex=True)
        )

    # Quitar última fila (fila combinada/resumen)
    if len(df) > 0:
        df = df.iloc[:-1].copy()

    dfs_pedidos.append(df)

movimientos_pedidos = pd.concat(dfs_pedidos, ignore_index=True)

print(f"Total de archivos leídos: {len(archivos_pedidos)}")
print(f"Forma del dataframe: {movimientos_pedidos.shape}")
movimientos_pedidos.head()

Total de archivos leídos: 12
Forma del dataframe: (175940, 25)

,Tipo movimiento,Fecha inicio,Pedido,Div. ped.,Pedido externo,Cliente,Cliente externo,Paleta,Unid. caja,U. ret.,...,VL,Denominación artículo,Código externo,V1 ext.,V2 ext.,VL ext.,Propietario,Operario,Denominación operario,Lote fabricación
0,PI,03/01/2022 08:25:01,39964.0,0.0,SGE202205972-01,750.0,GEM000000000009,400000010002700981,1.0,NaN,...,0.0,MESA BLANCA PATA MARRON TERRAZA MAHOU,E,NaN,NaN,NaN,34.0,260.0,MANUEL GARRIDO,NaN
1,PI,03/01/2022 08:31:38,39964.0,0.0,SGE202205972-01,750.0,GEM000000000009,400000010003252021,1.0,NaN,...,0.0,MESA BLANCA PATA MARRON TERRAZA MAHOU,E,NaN,NaN,NaN,34.0,260.0,MANUEL GARRIDO,NaN
2,PI,03/01/2022 08:35:23,39964.0,0.0,SGE202205972-01,750.0,GEM000000000009,400000010002700974,1.0,NaN,...,0.0,SILLA PLÁSTICO MARRÓN DESDE 1890 MAHOU,E,NaN,NaN,NaN,34.0,260.0,MANUEL GARRIDO,NaN
3,PI,03/01/2022 08:40:23,39964.0,0.0,SGE202205972-01,750.0,GEM000000000009,400000010003252052,1.0,NaN,...,0.0,SILLA PLÁSTICO MARRÓN DESDE 1890 MAHOU,E,NaN,NaN,NaN,34.0,260.0,MANUEL GARRIDO,NaN
4,PI,03/01/2022 08:43:26,39964.0,0.0,SGE202205972-01,750.0,GEM000000000009,400000010003252038,1.0,NaN,...,0.0,SILLA PLÁSTICO MARRÓN DESDE 1890 MAHOU,E,NaN,NaN,NaN,34.0,260.0,MANUEL GARRIDO,NaN

In [3]:
movimientos_pedidos

,Tipo movimiento,Fecha inicio,Pedido,Div. ped.,Pedido externo,Cliente,Cliente externo,Paleta,Unid. caja,U. ret.,...,VL,Denominación artículo,Código externo,V1 ext.,V2 ext.,VL ext.,Propietario,Operario,Denominación operario,Lote fabricación
0,PI,03/01/2022 08:25:01,39964.0,0.0,SGE202205972-01,750.0,GEM000000000009,400000010002700981,1.0,NaN,...,0.0,MESA BLANCA PATA MARRON TERRAZA MAHOU,E,NaN,NaN,NaN,34.0,260.0,MANUEL GARRIDO,NaN
1,PI,03/01/2022 08:31:38,39964.0,0.0,SGE202205972-01,750.0,GEM000000000009,400000010003252021,1.0,NaN,...,0.0,MESA BLANCA PATA MARRON TERRAZA MAHOU,E,NaN,NaN,NaN,34.0,260.0,MANUEL GARRIDO,NaN
2,PI,03/01/2022 08:35:23,39964.0,0.0,SGE202205972-01,750.0,GEM000000000009,400000010002700974,1.0,NaN,...,0.0,SILLA PLÁSTICO MARRÓN DESDE 1890 MAHOU,E,NaN,NaN,NaN,34.0,260.0,MANUEL GARRIDO,NaN
3,PI,03/01/2022 08:40:23,39964.0,0.0,SGE202205972-01,750.0,GEM000000000009,400000010003252052,1.0,NaN,...,0.0,SILLA PLÁSTICO MARRÓN DESDE 1890 MAHOU,E,NaN,NaN,NaN,34.0,260.0,MANUEL GARRIDO,NaN
4,PI,03/01/2022 08:43:26,39964.0,0.0,SGE202205972-01,750.0,GEM000000000009,400000010003252038,1.0,NaN,...,0.0,SILLA PLÁSTICO MARRÓN DESDE 1890 MAHOU,E,NaN,NaN,NaN,34.0,260.0,MANUEL GARRIDO,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175935,CR,30/12/2022 16:19:22,15376.0,NaN,M2323BLUESPACE,NaN,NaN,,1.0,NaN,...,0.0,CAMISETA T-M GRIS ERES LA CAÑA,E,NaN,NaN,NaN,33.0,236.0,RAFA SOTO,NaN
175936,CR,30/12/2022 16:19:22,15376.0,NaN,M2323BLUESPACE,NaN,NaN,,1.0,NaN,...,0.0,KARAOKE SUVZERO SZPA-P15 80W,E,NaN,NaN,NaN,33.0,236.0,RAFA SOTO,NaN
175937,CR,30/12/2022 16:19:22,15376.0,NaN,M2323BLUESPACE,NaN,NaN,,1.0,NaN,...,0.0,RADIO/ALTAVOZ MAHOU,NaN,NaN,NaN,NaN,33.0,236.0,RAFA SOTO,NaN
175938,EP,30/12/2022 17:37:57,15215.0,NaN,EGE202210673-01,NaN,NaN,400000110004686525,1.0,NaN,...,0.0,COPA 33CL MAHOU LOGO ROJO CERVEZAS,E,NaN,NaN,NaN,11.0,236.0,RAFA SOTO,NaN
175939,CR,30/12/2022 17:47:12,15380.0,NaN,10673FLORIDAPARK,NaN,NaN,,1.0,NaN,...,0.0,COPA 33CL ALHAMBRA ARRAYANES EVENTOS,E,NaN,NaN,NaN,11.0,236.0,RAFA SOTO,NaN

In [4]:
# Buscar la información de la fila con la paleta específica
paleta_buscada = "400000240005936814"
resultado = movimientos_pedidos[movimientos_pedidos['Paleta'] == paleta_buscada]
resultado

,Tipo movimiento,Fecha inicio,Pedido,Div. ped.,Pedido externo,Cliente,Cliente externo,Paleta,Unid. caja,U. ret.,...,VL,Denominación artículo,Código externo,V1 ext.,V2 ext.,VL ext.,Propietario,Operario,Denominación operario,Lote fabricación
102614,EP,28/09/2023 16:02:15,21279.0,NaN,EGE202314655-01,NaN,NaN,400000240005936814,NaN,NaN,...,0.0,MESA CUADRADA GRIS MAHOU PATA TRIPODE,E,NaN,NaN,NaN,24.0,237.0,EMILIO RODRIGO,NaN
131603,PI,30/11/2023 07:41:26,103657.0,0,SGE202316527-01,15525.0,GEM000000002803,400000240005936814,1.0,NaN,...,0.0,MESA CUADRADA GRIS MAHOU PATA TRIPODE,E,NaN,NaN,NaN,24.0,260.0,MANUEL GARRIDO,NaN

In [5]:
# Buscar la información de la fila con la paleta específica
paleta_buscada = "400000240005936814"
resultado = movimientos[movimientos['Paleta'] == paleta_buscada]
resultado

,Tipo movimiento,Fecha inicio,Fecha finalización,Artículo,Denominación artículo,Pas. Ori.,Col. Ori.,Alt. Ori.,Pas. Des.,Col. Des.,...,Unidades / Caja,Unidades / Retráctil,V1,V2,VL,Propietario,Operario,Denominación operario,Lote fabricación,Código externo
155698,EP,28/09/2023 16:02:15,28/09/2023 16:03:12,022177,MESA CUADRADA GRIS MAHOU PATA TRIPODE,NaN,301.0,NaN,020,144,...,NaN,NaN,0.0,0.0,0.0,24.0,237.0,EMILIO RODRIGO,NaN,NaN
206762,PI,30/11/2023 07:41:26,30/11/2023 07:47:16,022177,MESA CUADRADA GRIS MAHOU PATA TRIPODE,020,144.0,30.0,NaN,2,...,1.0,NaN,0.0,0.0,0.0,24.0,260.0,MANUEL GARRIDO,NaN,NaN

In [6]:
movimientos_pedidos

,Tipo movimiento,Fecha inicio,Pedido,Div. ped.,Pedido externo,Cliente,Cliente externo,Paleta,Unid. caja,U. ret.,...,VL,Denominación artículo,Código externo,V1 ext.,V2 ext.,VL ext.,Propietario,Operario,Denominación operario,Lote fabricación
0,PI,03/01/2022 08:25:01,39964.0,0.0,SGE202205972-01,750.0,GEM000000000009,400000010002700981,1.0,NaN,...,0.0,MESA BLANCA PATA MARRON TERRAZA MAHOU,E,NaN,NaN,NaN,34.0,260.0,MANUEL GARRIDO,NaN
1,PI,03/01/2022 08:31:38,39964.0,0.0,SGE202205972-01,750.0,GEM000000000009,400000010003252021,1.0,NaN,...,0.0,MESA BLANCA PATA MARRON TERRAZA MAHOU,E,NaN,NaN,NaN,34.0,260.0,MANUEL GARRIDO,NaN
2,PI,03/01/2022 08:35:23,39964.0,0.0,SGE202205972-01,750.0,GEM000000000009,400000010002700974,1.0,NaN,...,0.0,SILLA PLÁSTICO MARRÓN DESDE 1890 MAHOU,E,NaN,NaN,NaN,34.0,260.0,MANUEL GARRIDO,NaN
3,PI,03/01/2022 08:40:23,39964.0,0.0,SGE202205972-01,750.0,GEM000000000009,400000010003252052,1.0,NaN,...,0.0,SILLA PLÁSTICO MARRÓN DESDE 1890 MAHOU,E,NaN,NaN,NaN,34.0,260.0,MANUEL GARRIDO,NaN
4,PI,03/01/2022 08:43:26,39964.0,0.0,SGE202205972-01,750.0,GEM000000000009,400000010003252038,1.0,NaN,...,0.0,SILLA PLÁSTICO MARRÓN DESDE 1890 MAHOU,E,NaN,NaN,NaN,34.0,260.0,MANUEL GARRIDO,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175935,CR,30/12/2022 16:19:22,15376.0,NaN,M2323BLUESPACE,NaN,NaN,,1.0,NaN,...,0.0,CAMISETA T-M GRIS ERES LA CAÑA,E,NaN,NaN,NaN,33.0,236.0,RAFA SOTO,NaN
175936,CR,30/12/2022 16:19:22,15376.0,NaN,M2323BLUESPACE,NaN,NaN,,1.0,NaN,...,0.0,KARAOKE SUVZERO SZPA-P15 80W,E,NaN,NaN,NaN,33.0,236.0,RAFA SOTO,NaN
175937,CR,30/12/2022 16:19:22,15376.0,NaN,M2323BLUESPACE,NaN,NaN,,1.0,NaN,...,0.0,RADIO/ALTAVOZ MAHOU,NaN,NaN,NaN,NaN,33.0,236.0,RAFA SOTO,NaN
175938,EP,30/12/2022 17:37:57,15215.0,NaN,EGE202210673-01,NaN,NaN,400000110004686525,1.0,NaN,...,0.0,COPA 33CL MAHOU LOGO ROJO CERVEZAS,E,NaN,NaN,NaN,11.0,236.0,RAFA SOTO,NaN
175939,CR,30/12/2022 17:47:12,15380.0,NaN,10673FLORIDAPARK,NaN,NaN,,1.0,NaN,...,0.0,COPA 33CL ALHAMBRA ARRAYANES EVENTOS,E,NaN,NaN,NaN,11.0,236.0,RAFA SOTO,NaN

In [7]:
# Eliminar columnas de movimientos
columnas_eliminar = ['F.', 'Código externo', 'V1', 'V2', 'VL', 'Lote fabricación', 'Unidades / Caja', 'Unidades / Retráctil']  # Modifica esta lista según necesites
movimientos = movimientos.drop(columns=columnas_eliminar, errors='ignore')

print(f"Columnas eliminadas: {columnas_eliminar}")
print(f"Forma del dataframe: {movimientos.shape}")
print(f"Columnas restantes: {movimientos.columns.tolist()}")

Columnas eliminadas: ['F.', 'Código externo', 'V1', 'V2', 'VL', 'Lote fabricación', 'Unidades / Caja', 'Unidades / Retráctil']
Forma del dataframe: (276044, 16)
Columnas restantes: ['Tipo movimiento', 'Fecha inicio', 'Fecha finalización', 'Artículo', 'Denominación artículo', 'Pas. Ori.', 'Col. Ori.', 'Alt. Ori.', 'Pas. Des.', 'Col. Des.', 'Alt. Des.', 'Paleta', 'Cantidad', 'Propietario', 'Operario', 'Denominación operario']

In [8]:
# CELDA 5 (Ubicacion correcta + regla 301)
cols = ['Pas. Ori.', 'Col. Ori.', 'Alt. Ori.']

for c in cols:
    movimientos[c] = pd.to_numeric(movimientos[c], errors='coerce')

mask_col_301 = movimientos['Col. Ori.'].eq(301)

movimientos['Ubicacion'] = pd.NA
mask_norm = movimientos[cols].notna().all(axis=1) & ~mask_col_301

movimientos.loc[mask_norm, 'Ubicacion'] = (
    movimientos.loc[mask_norm, 'Pas. Ori.'].astype('Int64').astype(str).str.zfill(3) + '-' +
    movimientos.loc[mask_norm, 'Col. Ori.'].astype('Int64').astype(str).str.zfill(3) + '-' +
    movimientos.loc[mask_norm, 'Alt. Ori.'].astype('Int64').astype(str).str.zfill(2)
)

movimientos.loc[mask_col_301, 'Ubicacion'] = '301'

movimientos[cols + ['Ubicacion']].head()

   Pas. Ori.  Col. Ori.  Alt. Ori.   Ubicacion
0        NaN        NaN        NaN        <NA>
1       15.0       87.0       20.0  015-087-20
2       20.0       74.0       10.0  020-074-10
3        NaN        NaN        NaN        <NA>
4        NaN        NaN        NaN        <NA>

In [9]:
# CELDA 6 (Paleta sin inventar valores)
import re

def _normaliza_paleta(v):
    if pd.isna(v):
        return ''
    s = str(v).strip()
    if s == '' or s.lower() in {'nan', 'none', '<na>'}:
        return ''
    if re.fullmatch(r'\d+\.0+', s):
        return s.split('.')[0]
    return s

for name, df in (('movimientos', movimientos),
                 ('movimientos_pedidos', movimientos_pedidos)):
    if 'Paleta' in df.columns:
        df['Paleta'] = df['Paleta'].map(_normaliza_paleta)
        print(f"{name} - primeros valores de Paleta:")
        print(df['Paleta'].head())

movimientos - primeros valores de Paleta:
0
1    400000010002700981
2    400000010003252021
3
4
Name: Paleta, dtype: object
movimientos_pedidos - primeros valores de Paleta:
0    400000010002700981
1    400000010003252021
2    400000010002700974
3    400000010003252052
4    400000010003252038
Name: Paleta, dtype: object

In [10]:
movimientos

,Tipo movimiento,Fecha inicio,Fecha finalización,Artículo,Denominación artículo,Pas. Ori.,Col. Ori.,Alt. Ori.,Pas. Des.,Col. Des.,Alt. Des.,Paleta,Cantidad,Propietario,Operario,Denominación operario,Ubicacion
0,CC,03/01/2022 08:24:57,03/01/2022 08:25:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,260.0,MANUEL GARRIDO,<NA>
1,PI,03/01/2022 08:25:01,03/01/2022 08:31:38,022043,MESA BLANCA PATA MARRON TERRAZA MAHOU,15.0,87.0,20.0,NaN,302,NaN,400000010002700981,6,34.0,260.0,MANUEL GARRIDO,015-087-20
2,PI,03/01/2022 08:31:38,03/01/2022 08:35:21,022043,MESA BLANCA PATA MARRON TERRAZA MAHOU,20.0,74.0,10.0,NaN,302,NaN,400000010003252021,19,34.0,260.0,MANUEL GARRIDO,020-074-10
3,CC,03/01/2022 08:35:22,03/01/2022 08:35:23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,260.0,MANUEL GARRIDO,<NA>
4,DC,03/01/2022 08:35:22,03/01/2022 08:35:22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,260.0,MANUEL GARRIDO,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
276039,PI,31/07/2024 20:02:30,31/07/2024 20:48:15,094000,TRASERA 2m ILUMINADA CON LOGO M MAHOU,19.0,74.0,0.0,NaN,2,NaN,400000230004431625,5.0,23.0,238.0,PAUL AYESTA,019-074-00
276040,PI,31/07/2024 20:48:15,31/07/2024 20:53:25,011105,CERVEZA 33CL MAHOU ROSE (5347),22.0,115.0,20.0,NaN,2,NaN,400000230006370687,24.0,23.0,238.0,PAUL AYESTA,022-115-20
276041,PI,31/07/2024 20:53:25,31/07/2024 20:55:08,011026,CERVEZA 33CLMAHOU IPA (3526),20.0,100.0,30.0,NaN,2,NaN,400000230006354724,24.0,23.0,238.0,PAUL AYESTA,020-100-30
276042,PI,31/07/2024 20:55:08,31/07/2024 21:00:28,011009,CERVEZA 33CL MAHOU BARRICA BOURBON,20.0,107.0,10.0,NaN,2,NaN,400000230006354571,24.0,23.0,238.0,PAUL AYESTA,020-107-10
276043,DC,31/07/2024 21:00:28,31/07/2024 21:00:29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,NaN,238.0,PAUL AYESTA,<NA>

In [11]:
# Eliminar columnas de movimientos_pedidos
columnas_eliminar_ped = ['F.', 'Código externo', 'V1', 'V2', 'VL', 'V1 ext.', 'V2 ext.', 'VL ext.', 'Div. ped.', 'Unid. caja', 'U. ret.', 'Denominación artículo', 'Propietario', 'Operario', 'Denominación operario', 'Lote fabricación','Tipo movimiento', 'Artículo']  # Modifica esta lista según necesites
movimientos_pedidos = movimientos_pedidos.drop(columns=columnas_eliminar_ped, errors='ignore')

print(f"Columnas eliminadas: {columnas_eliminar_ped}")
print(f"Forma del dataframe: {movimientos_pedidos.shape}")
print(f"Columnas restantes: {movimientos_pedidos.columns.tolist()}")

Columnas eliminadas: ['F.', 'Código externo', 'V1', 'V2', 'VL', 'V1 ext.', 'V2 ext.', 'VL ext.', 'Div. ped.', 'Unid. caja', 'U. ret.', 'Denominación artículo', 'Propietario', 'Operario', 'Denominación operario', 'Lote fabricación', 'Tipo movimiento', 'Artículo']
Forma del dataframe: (175940, 7)
Columnas restantes: ['Fecha inicio', 'Pedido', 'Pedido externo', 'Cliente', 'Cliente externo', 'Paleta', 'Cantidad']

In [12]:
movimientos_pedidos

,Fecha inicio,Pedido,Pedido externo,Cliente,Cliente externo,Paleta,Cantidad
0,03/01/2022 08:25:01,39964.0,SGE202205972-01,750.0,GEM000000000009,400000010002700981,6.0
1,03/01/2022 08:31:38,39964.0,SGE202205972-01,750.0,GEM000000000009,400000010003252021,19.0
2,03/01/2022 08:35:23,39964.0,SGE202205972-01,750.0,GEM000000000009,400000010002700974,26.0
3,03/01/2022 08:40:23,39964.0,SGE202205972-01,750.0,GEM000000000009,400000010003252052,26.0
4,03/01/2022 08:43:26,39964.0,SGE202205972-01,750.0,GEM000000000009,400000010003252038,26.0
...,...,...,...,...,...,...,...
175935,30/12/2022 16:19:22,15376.0,M2323BLUESPACE,NaN,NaN,,12.0
175936,30/12/2022 16:19:22,15376.0,M2323BLUESPACE,NaN,NaN,,1.0
175937,30/12/2022 16:19:22,15376.0,M2323BLUESPACE,NaN,NaN,,4.0
175938,30/12/2022 17:37:57,15215.0,EGE202210673-01,NaN,NaN,400000110004686525,1.08
175939,30/12/2022 17:47:12,15380.0,10673FLORIDAPARK,NaN,NaN,,276.0

In [13]:
keys = ['Fecha inicio', 'Paleta', 'Cantidad']

# normalizar tipos/formato en ambas tablas
for df in (movimientos, movimientos_pedidos):
    df['Paleta'] = (
        df['Paleta']
        .astype('string')
        .str.strip()
        .fillna('')
        .replace({'<NA>': '', 'nan': '', 'None': ''})
    )
    df['Cantidad'] = pd.to_numeric(df['Cantidad'], errors='coerce')
    df['Fecha inicio'] = pd.to_datetime(df['Fecha inicio'], errors='coerce', dayfirst=True)

    # Si quieres que compare solo fecha (ignorando hora), descomenta:
    # df['Fecha inicio'] = df['Fecha inicio'].dt.normalize()

# evitar duplicados en la derecha para que no se multipliquen filas
movimientos_pedidos_u = movimientos_pedidos.drop_duplicates(subset=keys)

# merge horizontal: conserva todas las filas de movimientos
movimientos_merge = movimientos.merge(
    movimientos_pedidos_u,
    on=keys,
    how='left',
    suffixes=('', '_pedido')
)

movimientos_merge

,Tipo movimiento,Fecha inicio,Fecha finalización,Artículo,Denominación artículo,Pas. Ori.,Col. Ori.,Alt. Ori.,Pas. Des.,Col. Des.,...,Paleta,Cantidad,Propietario,Operario,Denominación operario,Ubicacion,Pedido,Pedido externo,Cliente,Cliente externo
0,CC,2022-01-03 08:24:57,03/01/2022 08:25:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,NaN,NaN,260.0,MANUEL GARRIDO,<NA>,NaN,NaN,NaN,NaN
1,PI,2022-01-03 08:25:01,03/01/2022 08:31:38,022043,MESA BLANCA PATA MARRON TERRAZA MAHOU,15.0,87.0,20.0,NaN,302,...,400000010002700981,6.0,34.0,260.0,MANUEL GARRIDO,015-087-20,39964.0,SGE202205972-01,750.0,GEM000000000009
2,PI,2022-01-03 08:31:38,03/01/2022 08:35:21,022043,MESA BLANCA PATA MARRON TERRAZA MAHOU,20.0,74.0,10.0,NaN,302,...,400000010003252021,19.0,34.0,260.0,MANUEL GARRIDO,020-074-10,39964.0,SGE202205972-01,750.0,GEM000000000009
3,CC,2022-01-03 08:35:22,03/01/2022 08:35:23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,NaN,NaN,260.0,MANUEL GARRIDO,<NA>,NaN,NaN,NaN,NaN
4,DC,2022-01-03 08:35:22,03/01/2022 08:35:22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,NaN,NaN,260.0,MANUEL GARRIDO,<NA>,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
276039,PI,2024-07-31 20:02:30,31/07/2024 20:48:15,094000,TRASERA 2m ILUMINADA CON LOGO M MAHOU,19.0,74.0,0.0,NaN,2,...,400000230004431625,5.0,23.0,238.0,PAUL AYESTA,019-074-00,128659.0,NaN,29622.0,GEM000000009272
276040,PI,2024-07-31 20:48:15,31/07/2024 20:53:25,011105,CERVEZA 33CL MAHOU ROSE (5347),22.0,115.0,20.0,NaN,2,...,400000230006370687,24.0,23.0,238.0,PAUL AYESTA,022-115-20,128659.0,NaN,29622.0,GEM000000009272
276041,PI,2024-07-31 20:53:25,31/07/2024 20:55:08,011026,CERVEZA 33CLMAHOU IPA (3526),20.0,100.0,30.0,NaN,2,...,400000230006354724,24.0,23.0,238.0,PAUL AYESTA,020-100-30,128659.0,NaN,29622.0,GEM000000009272
276042,PI,2024-07-31 20:55:08,31/07/2024 21:00:28,011009,CERVEZA 33CL MAHOU BARRICA BOURBON,20.0,107.0,10.0,NaN,2,...,400000230006354571,24.0,23.0,238.0,PAUL AYESTA,020-107-10,128659.0,NaN,29622.0,GEM000000009272
276043,DC,2024-07-31 21:00:28,31/07/2024 21:00:29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,NaN,NaN,238.0,PAUL AYESTA,<NA>,NaN,NaN,NaN,NaN

In [15]:
import re
import pandas as pd

def normalizar_pedido_externo(v):
    if pd.isna(v):
        return ''
    s = str(v).strip()
    if s == '' or s.lower() in {'nan', 'none', '<na>'}:
        return ''

    s_up = s.upper()

    # 1) SGE/EGE/SGP + dígitos (corta sufijos tipo -01, /24, espacio, etc.)
    m = re.match(r'^(SGE|EGE|SGP)(\d+)', s_up)
    if m:
        return f"{m.group(1)}{m.group(2)}"

    # 2) E0M2506/... -> M2506
    m = re.match(r'^E0(M\d{4})', s_up)
    if m:
        return m.group(1)

    # 3) M2506/1 (o M2506-1) -> M2506
    m = re.match(r'^(M\d{4})', s_up)
    if m:
        return m.group(1)

    # 4) resto: sin cambios
    return s

# Aplicar en dataframes disponibles y en cualquier columna "Pedido externo*"
for nombre_df in ('movimientos_pedidos', 'movimientos_merge'):
    if nombre_df in globals():
        df = globals()[nombre_df]
        cols_objetivo = [c for c in df.columns if c.startswith('Pedido externo')]
        for col in cols_objetivo:
            antes = df[col].astype('string').fillna('')
            df[col] = df[col].map(normalizar_pedido_externo)
            cambios = int((antes != df[col].astype('string').fillna('')).sum())
            print(f"{nombre_df}.{col}: {cambios} valores normalizados")

movimientos_pedidos.Pedido externo: 116335 valores normalizados
movimientos_merge.Pedido externo: 116431 valores normalizados

In [16]:
movimientos_merge.to_excel(r'c:\Users\rdiezl\Desktop\proyecto\planificacion\Datos\movimientos.xlsx', index=False)