In [1]:
import pandas as pd
import os
from pathlib import Path

# Ruta a la carpeta de Albaranes
ruta_albaranes = r'c:\Users\rdiezl\Desktop\proyecto\planificacion\Datos\Albaranes'

# Leer todos los archivos .xlsx
archivos = [f for f in os.listdir(ruta_albaranes) if f.endswith('.xlsx')]
dataframes = [pd.read_excel(os.path.join(ruta_albaranes, archivo)) for archivo in archivos]

# Combinar todos los dataframes en uno solo
df1 = pd.concat(dataframes, ignore_index=True)

In [2]:
# Ruta a la carpeta de Portes
ruta_portes = r'c:\Users\rdiezl\Desktop\proyecto\planificacion\Datos\Portes'

# Leer todos los archivos .xlsx
archivos_portes = [f for f in os.listdir(ruta_portes) if f.endswith('.xlsx')]
dataframes_portes = [pd.read_excel(os.path.join(ruta_portes, archivo)) for archivo in archivos_portes]

# Combinar todos los dataframes en uno solo
df2 = pd.concat(dataframes_portes, ignore_index=True)

In [3]:
df1

,ITEM,FECHA SERVICIO,CONCEPTO (DENOMINACIÓN EVENTO ASOCIADO),DESCRIPCIÓN,SOLICITANTE MAHOU,DPTO MAHOU,CIF FACTURACIÓN,PALÉS IN,CAJAS IN,M3 IN,...,DISTANCIA EVENTO A ALMACÉN (KM),KM EXTRA,HORAS EXTRA,NOCHES DESPLAZAM X OPERARIO,LAVADO COPAS (EXCEPTO MENTORING),PRESUPUESTO PARTICULAR,EMPRESA,MES,AÑO,CP
0,35372.0,NaT,NaN,EXPEDICIÓN E0/2022,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,2022.0,NaN
1,32145.0,NaT,NaN,EXPEDICIÓN E0100000/2022,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,2022.0,NaN
2,34186.0,2023-05-01,PORTE ENVIO PRODUCTO GANADOR PAULA LOPEZ JIMEN...,EXPEDICIÓN E023/2022,BEATRIZ DONOSO,MAHOU,A28078202,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,PAULA LOPEZ JIMENEZ,8.0,2022.0,30165
3,34185.0,2023-04-03,PORTE ENVIO PRODUCTO GANADOR PAULA LOPEZ JIMEN...,EXPEDICIÓN E024/2022,BEATRIZ DONOSO,MAHOU,A28078202,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,PAULA LOPEZ JIMENEZ,8.0,2022.0,30165
4,30235.0,2022-01-18,PORTE ENTREGA MOSTRADOR FITUR STAND ALCALA DE ...,EXPEDICIÓN E024375/2022,ALBA GARCIA,DCMC – Madrid,A28078202,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,FITUR STAND ALCALA DE HENARES,1.0,2022.0,28042
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23548,52637.0,2024-12-30,PORTE ENVIO URGENTE GPI,EXPEDICIÓN E0SGP202523811/2024,GIULIA ARNOLS,RODAJE 5 ESTRELLAS,A28078202,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,GPI,12.0,2024.0,8711
23549,52633.0,2024-12-30,PORTE ENTREGA URGENTE SAICA,EXPEDICIÓN E0SGP202523812/2024,GIULIA ARNOLS,RODAJE 5 ESTRELLAS,A28078202,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Saica,12.0,2024.0,28108
23550,52634.0,2024-12-30,PORTE ENTREGA URGENTE NEW BOX,EXPEDICIÓN E0SGP202523815/2024,GIULIA ARNOLS,RODAJE 5 ESTRELLAS,A28078202,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Ibertapon,12.0,2024.0,28025
23551,52640.0,2025-01-03,PORTE ENTREGA GRIFO ECESA,EXPEDICIÓN E0SGP202523817/2025,BEATRIZ DONOSO,MAHOU,A28078202,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,ECESA,1.0,2025.0,28906
23552,52653.0,2025-03-18,EXPEDICION BOTELLERO BETO TORRES Y CARRERA,EXPEDICIÓN E0SGP202523821/2025,JESUS MANUEL SAEZ,MAHOU GALICIA Y ASTURIAS,A28078202,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,SERVICIO MOVIL VIGO,3.0,2025.0,36416 - PONTEVEDRA

In [4]:
## saber los valores diferentes de la columna palés in
df1['PALÉS IN'].unique()

array([ nan,   1.,   5.,   4.,  21.,   7.,  23.,   6.,   8.,  15.,   9.,
        10.,   3.,  14.,  35.,   2.,  17.,  30.,  16.,  19.,  39.,  25.,
        13.,  20.,  12.,  11.,  28.,  45., 148.,  26.,  27.,  24.,  22.,
        18.,  50.,  37.,  60.,  40.,  55.,  29.,  31., 120.,  80.,  33.,
        71.,  70.,  76.,  41.,  77.,  43.,  32.,  64.,  44.,  99.,  92.,
        54.,  47.,  83.,  87.,  66.,  36.,  42.,  97.,  85.,  48.,  91.,
        34.,  38.,  56.,  63.,  46.,  53.])

In [5]:
df2

,DESCRIPCIÓN,URGENCIA,FESTIVO,PROVINCIA DESTINO,TIEMPO RELOJ TRANSPORTE (HORAS),TIEMPO RELOJ CARGA Y DESCARGA (HORAS),Nº OPERARIOS (SIN CONTAR CHÓFER),PESO (KG),LARGO (cm),ANCHO (cm),ALTO (cm)
0,EXPEDICIÓN E0,NO,NO,Madrid,0.0,3.0,2.0,1500.0,100.0,100.0,2500.0
1,EXPEDICIÓN E00001/2020,NO,NO,Madrid,1.0,0.3,0.0,80.0,100.0,100.0,50.0
2,EXPEDICIÓN E00003/2020,NO,NO,Madrid,1.0,1.3,1.0,650.0,100.0,100.0,250.0
3,EXPEDICIÓN E00004/2020,NO,NO,Madrid,1.0,1.0,1.0,650.0,100.0,100.0,250.0
4,EXPEDICIÓN E00005/2020,NO,NO,Madrid,1.0,0.7,1.0,550.0,100.0,100.0,400.0
...,...,...,...,...,...,...,...,...,...,...,...
26735,EXPEDICIÓN E0SGP202523811/2024,NO,NO,Barcelona,0.0,0.0,0.0,180.0,100.0,100.0,40.0
26736,EXPEDICIÓN E0SGP202523812/2024,NO,NO,Madrid,1.0,0.7,0.0,180.0,100.0,100.0,40.0
26737,EXPEDICIÓN E0SGP202523815/2024,NO,NO,Madrid,1.0,0.7,1.0,180.0,100.0,100.0,40.0
26738,EXPEDICIÓN E0SGP202523817/2025,NO,NO,Madrid,1.0,0.3,0.0,15.0,100.0,100.0,4.0
26739,SGP202421,NO,NO,Madrid,1.0,1.3,1.0,600.0,100.0,100.0,900.0

In [6]:
# Merge horizontal de df1 y df2 por la columna 'DESCRIPCIÓN'
df_merged = pd.merge(df1, df2, on='DESCRIPCIÓN', how='left')
df_merged

,ITEM,FECHA SERVICIO,CONCEPTO (DENOMINACIÓN EVENTO ASOCIADO),DESCRIPCIÓN,SOLICITANTE MAHOU,DPTO MAHOU,CIF FACTURACIÓN,PALÉS IN,CAJAS IN,M3 IN,...,URGENCIA,FESTIVO,PROVINCIA DESTINO,TIEMPO RELOJ TRANSPORTE (HORAS),TIEMPO RELOJ CARGA Y DESCARGA (HORAS),Nº OPERARIOS (SIN CONTAR CHÓFER),PESO (KG),LARGO (cm),ANCHO (cm),ALTO (cm)
0,35372.0,NaT,NaN,EXPEDICIÓN E0/2022,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,32145.0,NaT,NaN,EXPEDICIÓN E0100000/2022,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,34186.0,2023-05-01,PORTE ENVIO PRODUCTO GANADOR PAULA LOPEZ JIMEN...,EXPEDICIÓN E023/2022,BEATRIZ DONOSO,MAHOU,A28078202,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,34185.0,2023-04-03,PORTE ENVIO PRODUCTO GANADOR PAULA LOPEZ JIMEN...,EXPEDICIÓN E024/2022,BEATRIZ DONOSO,MAHOU,A28078202,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,30235.0,2022-01-18,PORTE ENTREGA MOSTRADOR FITUR STAND ALCALA DE ...,EXPEDICIÓN E024375/2022,ALBA GARCIA,DCMC – Madrid,A28078202,NaN,NaN,NaN,...,NO,NO,Madrid,1.0,0.7,1.0,140.0,100.0,100.0,150.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23548,52637.0,2024-12-30,PORTE ENVIO URGENTE GPI,EXPEDICIÓN E0SGP202523811/2024,GIULIA ARNOLS,RODAJE 5 ESTRELLAS,A28078202,NaN,NaN,NaN,...,NO,NO,Barcelona,0.0,0.0,0.0,180.0,100.0,100.0,40.0
23549,52633.0,2024-12-30,PORTE ENTREGA URGENTE SAICA,EXPEDICIÓN E0SGP202523812/2024,GIULIA ARNOLS,RODAJE 5 ESTRELLAS,A28078202,NaN,NaN,NaN,...,NO,NO,Madrid,1.0,0.7,0.0,180.0,100.0,100.0,40.0
23550,52634.0,2024-12-30,PORTE ENTREGA URGENTE NEW BOX,EXPEDICIÓN E0SGP202523815/2024,GIULIA ARNOLS,RODAJE 5 ESTRELLAS,A28078202,NaN,NaN,NaN,...,NO,NO,Madrid,1.0,0.7,1.0,180.0,100.0,100.0,40.0
23551,52640.0,2025-01-03,PORTE ENTREGA GRIFO ECESA,EXPEDICIÓN E0SGP202523817/2025,BEATRIZ DONOSO,MAHOU,A28078202,NaN,NaN,NaN,...,NO,NO,Madrid,1.0,0.3,0.0,15.0,100.0,100.0,4.0
23552,52653.0,2025-03-18,EXPEDICION BOTELLERO BETO TORRES Y CARRERA,EXPEDICIÓN E0SGP202523821/2025,JESUS MANUEL SAEZ,MAHOU GALICIA Y ASTURIAS,A28078202,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df_merged['PALÉS IN'].unique()

array([ nan,   1.,   5.,   4.,  21.,   7.,  23.,   6.,   8.,  15.,   9.,
        10.,   3.,  14.,  35.,   2.,  17.,  30.,  16.,  19.,  39.,  25.,
        13.,  20.,  12.,  11.,  28.,  45., 148.,  26.,  27.,  24.,  22.,
        18.,  50.,  37.,  60.,  40.,  55.,  29.,  31., 120.,  80.,  33.,
        71.,  70.,  76.,  41.,  77.,  43.,  32.,  64.,  44.,  99.,  92.,
        54.,  47.,  83.,  87.,  66.,  36.,  42.,  97.,  85.,  48.,  91.,
        34.,  38.,  56.,  63.,  46.,  53.])

In [8]:
#df_merged.to_excel(r'c:\Users\rdiezl\Desktop\proyecto\planificacion\Datos\Albaranes_Portes_Merged.xlsx', index=False)

In [9]:
# Eliminar columnas específicas de df_merged
columnas_a_eliminar = ['CIF FACTURACIÓN', 'ALBARÁN OUT', 'HUECOS PALÉ', 'M2 SUELO', 'EVENTOS "A" NORMAL', 'EVENTOS "A" FESTIVO', 'EVENTOS "B" NORMAL', 'EVENTOS "B" FESTIVO', 'MENTORING 2 PERSONAS JUEVES LABORABLE', 'MENTORING 3 PERSONAS JUEVES LABORABLE', 'MENTORING 2 PERSONAS JUEVES FESTIVO', 'MENTORING 3 PERSONAS JUEVES FESTIVO', 'DISTANCIA EVENTO A ALMACÉN (KM)', 'KM EXTRA', 'HORAS EXTRA', 'LAVADO COPAS (EXCEPTO MENTORING)', 'PRESUPUESTO PARTICULAR', 'EMPRESA', 'MES', 'AÑO']
df_merged_limpio = df_merged.drop(columns=columnas_a_eliminar, errors='ignore')
df_merged_limpio

,ITEM,FECHA SERVICIO,CONCEPTO (DENOMINACIÓN EVENTO ASOCIADO),DESCRIPCIÓN,SOLICITANTE MAHOU,DPTO MAHOU,PALÉS IN,CAJAS IN,M3 IN,PALÉS OUT,...,URGENCIA,FESTIVO,PROVINCIA DESTINO,TIEMPO RELOJ TRANSPORTE (HORAS),TIEMPO RELOJ CARGA Y DESCARGA (HORAS),Nº OPERARIOS (SIN CONTAR CHÓFER),PESO (KG),LARGO (cm),ANCHO (cm),ALTO (cm)
0,35372.0,NaT,NaN,EXPEDICIÓN E0/2022,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,32145.0,NaT,NaN,EXPEDICIÓN E0100000/2022,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,34186.0,2023-05-01,PORTE ENVIO PRODUCTO GANADOR PAULA LOPEZ JIMEN...,EXPEDICIÓN E023/2022,BEATRIZ DONOSO,MAHOU,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,34185.0,2023-04-03,PORTE ENVIO PRODUCTO GANADOR PAULA LOPEZ JIMEN...,EXPEDICIÓN E024/2022,BEATRIZ DONOSO,MAHOU,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,30235.0,2022-01-18,PORTE ENTREGA MOSTRADOR FITUR STAND ALCALA DE ...,EXPEDICIÓN E024375/2022,ALBA GARCIA,DCMC – Madrid,NaN,NaN,NaN,NaN,...,NO,NO,Madrid,1.0,0.7,1.0,140.0,100.0,100.0,150.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23548,52637.0,2024-12-30,PORTE ENVIO URGENTE GPI,EXPEDICIÓN E0SGP202523811/2024,GIULIA ARNOLS,RODAJE 5 ESTRELLAS,NaN,NaN,NaN,1.0,...,NO,NO,Barcelona,0.0,0.0,0.0,180.0,100.0,100.0,40.0
23549,52633.0,2024-12-30,PORTE ENTREGA URGENTE SAICA,EXPEDICIÓN E0SGP202523812/2024,GIULIA ARNOLS,RODAJE 5 ESTRELLAS,NaN,NaN,NaN,1.0,...,NO,NO,Madrid,1.0,0.7,0.0,180.0,100.0,100.0,40.0
23550,52634.0,2024-12-30,PORTE ENTREGA URGENTE NEW BOX,EXPEDICIÓN E0SGP202523815/2024,GIULIA ARNOLS,RODAJE 5 ESTRELLAS,NaN,NaN,NaN,1.0,...,NO,NO,Madrid,1.0,0.7,1.0,180.0,100.0,100.0,40.0
23551,52640.0,2025-01-03,PORTE ENTREGA GRIFO ECESA,EXPEDICIÓN E0SGP202523817/2025,BEATRIZ DONOSO,MAHOU,NaN,NaN,NaN,NaN,...,NO,NO,Madrid,1.0,0.3,0.0,15.0,100.0,100.0,4.0
23552,52653.0,2025-03-18,EXPEDICION BOTELLERO BETO TORRES Y CARRERA,EXPEDICIÓN E0SGP202523821/2025,JESUS MANUEL SAEZ,MAHOU GALICIA Y ASTURIAS,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# Analizar valores de la columna DESCRIPCIÓN
print("Primeros 10 valores de DESCRIPCIÓN:")
print(df_merged_limpio['DESCRIPCIÓN'].head(10))
print("\n" + "="*50 + "\n")
print("Valores únicos (muestra):")
print(df_merged_limpio['DESCRIPCIÓN'].unique()[:10])

Primeros 10 valores de DESCRIPCIÓN:
0          EXPEDICIÓN E0/2022
1    EXPEDICIÓN E0100000/2022
2        EXPEDICIÓN E023/2022
3        EXPEDICIÓN E024/2022
4     EXPEDICIÓN E024375/2022
5     EXPEDICIÓN E038886/2022
6     EXPEDICIÓN E039470/2022
7     EXPEDICIÓN E040274/2022
8     EXPEDICIÓN E040277/2022
9     EXPEDICIÓN E040507/2022
Name: DESCRIPCIÓN, dtype: object

==================================================

Valores únicos (muestra):
['EXPEDICIÓN E0/2022' 'EXPEDICIÓN E0100000/2022' 'EXPEDICIÓN E023/2022'
 'EXPEDICIÓN E024/2022' 'EXPEDICIÓN E024375/2022'
 'EXPEDICIÓN E038886/2022' 'EXPEDICIÓN E039470/2022'
 'EXPEDICIÓN E040274/2022' 'EXPEDICIÓN E040277/2022'
 'EXPEDICIÓN E040507/2022']

In [11]:
# Normalizar la columna DESCRIPCIÓN
# Quitar 'EXPEDICIÓN E0' del principio y '/año' del final
df_merged_limpio['DESCRIPCIÓN'] = (df_merged_limpio['DESCRIPCIÓN']
                                   .str.replace('EXPEDICIÓN E0', '', regex=False)
                                   .str.replace(r'/\d{4}$', '', regex=True)
                                   .str.strip())

print("Valores después de normalizar:")
print(df_merged_limpio['DESCRIPCIÓN'].head(10))
print("\n" + "="*50 + "\n")
print("Valores únicos (muestra):")
print(df_merged_limpio['DESCRIPCIÓN'].unique()[:10])

Valores después de normalizar:
0
1    100000
2        23
3        24
4     24375
5     38886
6     39470
7     40274
8     40277
9     40507
Name: DESCRIPCIÓN, dtype: object

==================================================

Valores únicos (muestra):
['' '100000' '23' '24' '24375' '38886' '39470' '40274' '40277' '40507']

In [12]:
df_merged_limpio

,ITEM,FECHA SERVICIO,CONCEPTO (DENOMINACIÓN EVENTO ASOCIADO),DESCRIPCIÓN,SOLICITANTE MAHOU,DPTO MAHOU,PALÉS IN,CAJAS IN,M3 IN,PALÉS OUT,...,URGENCIA,FESTIVO,PROVINCIA DESTINO,TIEMPO RELOJ TRANSPORTE (HORAS),TIEMPO RELOJ CARGA Y DESCARGA (HORAS),Nº OPERARIOS (SIN CONTAR CHÓFER),PESO (KG),LARGO (cm),ANCHO (cm),ALTO (cm)
0,35372.0,NaT,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,32145.0,NaT,NaN,100000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,34186.0,2023-05-01,PORTE ENVIO PRODUCTO GANADOR PAULA LOPEZ JIMEN...,23,BEATRIZ DONOSO,MAHOU,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,34185.0,2023-04-03,PORTE ENVIO PRODUCTO GANADOR PAULA LOPEZ JIMEN...,24,BEATRIZ DONOSO,MAHOU,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,30235.0,2022-01-18,PORTE ENTREGA MOSTRADOR FITUR STAND ALCALA DE ...,24375,ALBA GARCIA,DCMC – Madrid,NaN,NaN,NaN,NaN,...,NO,NO,Madrid,1.0,0.7,1.0,140.0,100.0,100.0,150.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23548,52637.0,2024-12-30,PORTE ENVIO URGENTE GPI,SGP202523811,GIULIA ARNOLS,RODAJE 5 ESTRELLAS,NaN,NaN,NaN,1.0,...,NO,NO,Barcelona,0.0,0.0,0.0,180.0,100.0,100.0,40.0
23549,52633.0,2024-12-30,PORTE ENTREGA URGENTE SAICA,SGP202523812,GIULIA ARNOLS,RODAJE 5 ESTRELLAS,NaN,NaN,NaN,1.0,...,NO,NO,Madrid,1.0,0.7,0.0,180.0,100.0,100.0,40.0
23550,52634.0,2024-12-30,PORTE ENTREGA URGENTE NEW BOX,SGP202523815,GIULIA ARNOLS,RODAJE 5 ESTRELLAS,NaN,NaN,NaN,1.0,...,NO,NO,Madrid,1.0,0.7,1.0,180.0,100.0,100.0,40.0
23551,52640.0,2025-01-03,PORTE ENTREGA GRIFO ECESA,SGP202523817,BEATRIZ DONOSO,MAHOU,NaN,NaN,NaN,NaN,...,NO,NO,Madrid,1.0,0.3,0.0,15.0,100.0,100.0,4.0
23552,52653.0,2025-03-18,EXPEDICION BOTELLERO BETO TORRES Y CARRERA,SGP202523821,JESUS MANUEL SAEZ,MAHOU GALICIA Y ASTURIAS,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
# Calcular volumen y posicionar la columna a la derecha de PESO (KG)
# Calcular volumen en m³ (convertir de cm³ a m³)
df_merged_limpio['Volumen'] = (df_merged_limpio['LARGO (cm)'] * df_merged_limpio['ANCHO (cm)'] * df_merged_limpio['ALTO (cm)']) / 1000000

# Encontrar la posición de PESO (KG)
posicion_peso = df_merged_limpio.columns.get_loc('PESO (KG)')

# Reordenar columnas: sacar Volumen y colocarla después de PESO (KG)
cols = df_merged_limpio.columns.tolist()
cols.remove('Volumen')
cols.insert(posicion_peso + 1, 'Volumen')
df_merged_limpio = df_merged_limpio[cols]

# Eliminar las columnas de dimensiones en cm
df_merged_limpio = df_merged_limpio.drop(columns=['LARGO (cm)', 'ANCHO (cm)', 'ALTO (cm)'], errors='ignore')

print("Columnas después de eliminar dimensiones:")
print(df_merged_limpio.columns.tolist())
print("\nEjemplo con PESO y VOLUMEN:")
print(df_merged_limpio[['PESO (KG)', 'Volumen']].head(10))
df_merged_limpio

Columnas después de eliminar dimensiones:
['ITEM', 'FECHA SERVICIO', 'CONCEPTO (DENOMINACIÓN EVENTO ASOCIADO)', 'DESCRIPCIÓN', 'SOLICITANTE MAHOU', 'DPTO MAHOU', 'PALÉS IN', 'CAJAS IN', 'M3 IN', 'PALÉS OUT', 'CAJAS SIN MANIPULACIÓN', 'CAJAS CON MANIPULACIÓN', 'EMBALAJE CON MANIPULACIÓN', 'M3 OUT', 'NOCHES DESPLAZAM X OPERARIO', 'CP', 'URGENCIA', 'FESTIVO', 'PROVINCIA DESTINO', 'TIEMPO RELOJ TRANSPORTE (HORAS)', 'TIEMPO RELOJ CARGA Y DESCARGA (HORAS)', 'Nº OPERARIOS (SIN CONTAR CHÓFER)', 'PESO (KG)', 'Volumen']

Ejemplo con PESO y VOLUMEN:
   PESO (KG)  Volumen
0        NaN      NaN
1        NaN      NaN
2        NaN      NaN
3        NaN      NaN
4      140.0     1.50
5        NaN      NaN
6       15.0     0.03
7        NaN      NaN
8       68.0     0.20
9       15.0     0.03

,ITEM,FECHA SERVICIO,CONCEPTO (DENOMINACIÓN EVENTO ASOCIADO),DESCRIPCIÓN,SOLICITANTE MAHOU,DPTO MAHOU,PALÉS IN,CAJAS IN,M3 IN,PALÉS OUT,...,NOCHES DESPLAZAM X OPERARIO,CP,URGENCIA,FESTIVO,PROVINCIA DESTINO,TIEMPO RELOJ TRANSPORTE (HORAS),TIEMPO RELOJ CARGA Y DESCARGA (HORAS),Nº OPERARIOS (SIN CONTAR CHÓFER),PESO (KG),Volumen
0,35372.0,NaT,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,32145.0,NaT,NaN,100000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,34186.0,2023-05-01,PORTE ENVIO PRODUCTO GANADOR PAULA LOPEZ JIMEN...,23,BEATRIZ DONOSO,MAHOU,NaN,NaN,NaN,NaN,...,NaN,30165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,34185.0,2023-04-03,PORTE ENVIO PRODUCTO GANADOR PAULA LOPEZ JIMEN...,24,BEATRIZ DONOSO,MAHOU,NaN,NaN,NaN,NaN,...,NaN,30165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,30235.0,2022-01-18,PORTE ENTREGA MOSTRADOR FITUR STAND ALCALA DE ...,24375,ALBA GARCIA,DCMC – Madrid,NaN,NaN,NaN,NaN,...,NaN,28042,NO,NO,Madrid,1.0,0.7,1.0,140.0,1.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23548,52637.0,2024-12-30,PORTE ENVIO URGENTE GPI,SGP202523811,GIULIA ARNOLS,RODAJE 5 ESTRELLAS,NaN,NaN,NaN,1.0,...,NaN,8711,NO,NO,Barcelona,0.0,0.0,0.0,180.0,0.40
23549,52633.0,2024-12-30,PORTE ENTREGA URGENTE SAICA,SGP202523812,GIULIA ARNOLS,RODAJE 5 ESTRELLAS,NaN,NaN,NaN,1.0,...,NaN,28108,NO,NO,Madrid,1.0,0.7,0.0,180.0,0.40
23550,52634.0,2024-12-30,PORTE ENTREGA URGENTE NEW BOX,SGP202523815,GIULIA ARNOLS,RODAJE 5 ESTRELLAS,NaN,NaN,NaN,1.0,...,NaN,28025,NO,NO,Madrid,1.0,0.7,1.0,180.0,0.40
23551,52640.0,2025-01-03,PORTE ENTREGA GRIFO ECESA,SGP202523817,BEATRIZ DONOSO,MAHOU,NaN,NaN,NaN,NaN,...,NaN,28906,NO,NO,Madrid,1.0,0.3,0.0,15.0,0.04
23552,52653.0,2025-03-18,EXPEDICION BOTELLERO BETO TORRES Y CARRERA,SGP202523821,JESUS MANUEL SAEZ,MAHOU GALICIA Y ASTURIAS,NaN,NaN,NaN,NaN,...,NaN,36416 - PONTEVEDRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# Analizar los valores actuales de DESCRIPCIÓN para ver qué necesita corrección
print("Valores de DESCRIPCIÓN después de normalizacion:")
print("\nValores con SGE, EGE o SGP:")
sg_values = df_merged_limpio[df_merged_limpio['DESCRIPCIÓN'].str.contains('SGE|EGE|SGP', na=False, case=False)]['DESCRIPCIÓN'].unique()
for val in sg_values[:20]:
    print(f"'{val}' - Length: {len(val)}")

print("\nValores con M:")
m_values = df_merged_limpio[df_merged_limpio['DESCRIPCIÓN'].str.contains('M', na=False, case=False)]['DESCRIPCIÓN'].unique()
for val in m_values[:20]:
    print(f"'{val}' - Length: {len(val)}")

print("\nValores solo números:")
num_values = df_merged_limpio[df_merged_limpio['DESCRIPCIÓN'].str.match(r'^\d+$', na=False)]['DESCRIPCIÓN'].unique()
for val in num_values[:20]:
    print(f"'{val}' - Length: {len(val)}")

Valores de DESCRIPCIÓN después de normalizacion:

Valores con SGE, EGE o SGP:
'EGE02209400' - Length: 11
'EGE02210236' - Length: 11
'EGE20208245' - Length: 11
'EGE202206037' - Length: 12
'EGE202206724' - Length: 12
'EGE202206755/2' - Length: 14
'EGE202206755' - Length: 12
'EGE202206764' - Length: 12
'EGE202206797' - Length: 12
'EGE202206799' - Length: 12
'EGE202206805' - Length: 12
'EGE202206806' - Length: 12
'EGE202206810' - Length: 12
'EGE202206818' - Length: 12
'EGE202206819' - Length: 12
'EGE202206820' - Length: 12
'EGE202206848' - Length: 12
'EGE202206856' - Length: 12
'EGE202206859' - Length: 12
'EGE202206872' - Length: 12

Valores con M:
'M0001' - Length: 5
'M0002' - Length: 5
'M0003' - Length: 5
'M0004' - Length: 5
'M0005' - Length: 5
'M0006' - Length: 5
'M0007' - Length: 5
'M0008' - Length: 5
'M0009' - Length: 5
'M0010' - Length: 5
'M0011' - Length: 5
'M0012' - Length: 5
'M0013' - Length: 5
'M0014' - Length: 5
'M0015' - Length: 5
'M0016' - Length: 5
'M0017' - Length: 5
'M0018' - Length: 5
'M0019' - Length: 5
'M0020' - Length: 5

Valores solo números:
'100000' - Length: 6
'23' - Length: 2
'24' - Length: 2
'24375' - Length: 5
'38886' - Length: 5
'39470' - Length: 5
'40274' - Length: 5
'40277' - Length: 5
'40507' - Length: 5
'40525' - Length: 5
'40616' - Length: 5
'40625' - Length: 5
'40631' - Length: 5
'40634' - Length: 5
'40635' - Length: 5
'40650' - Length: 5
'40651' - Length: 5
'40652' - Length: 5
'40653' - Length: 5
'40654' - Length: 5

In [15]:
# Rehacemos el merge nuevamente para obtener los valores DESCRIPCIÓN original sin modificar
# Mantenemos df1 (Albaranes) a la LEFT y df2 (Portes) a la RIGHT para consistencia
df_merged_nuevo = pd.merge(df1, df2, on='DESCRIPCIÓN', how='left')

# Eliminamos las mismas columnas que antes
columnas_a_eliminar = ['CIF FACTURACIÓN', 'ALBARÁN OUT', 'HUECOS PALÉ', 'M2 SUELO', 'EVENTOS "A" NORMAL', 'EVENTOS "A" FESTIVO', 'EVENTOS "B" NORMAL', 'EVENTOS "B" FESTIVO', 'MENTORING 2 PERSONAS JUEVES LABORABLE', 'MENTORING 3 PERSONAS JUEVES LABORABLE', 'MENTORING 2 PERSONAS JUEVES FESTIVO', 'MENTORING 3 PERSONAS JUEVES FESTIVO', 'DISTANCIA EVENTO A ALMACÉN (KM)', 'KM EXTRA', 'HORAS EXTRA', 'LAVADO COPAS (EXCEPTO MENTORING)', 'PRESUPUESTO PARTICULAR', 'EMPRESA', 'MES', 'AÑO']
df_merged_nuevo = df_merged_nuevo.drop(columns=columnas_a_eliminar, errors='ignore')

# Reasignar el volumen al nuevo dataframe
df_merged_nuevo['Volumen'] = (df_merged_nuevo['LARGO (cm)'] * df_merged_nuevo['ANCHO (cm)'] * df_merged_nuevo['ALTO (cm)']) / 1000000

# Encontrar posición de PESO (KG) y reordenar
posicion_peso = df_merged_nuevo.columns.get_loc('PESO (KG)')
cols = df_merged_nuevo.columns.tolist()
if 'Volumen' in cols:
    cols.remove('Volumen')
cols.insert(posicion_peso + 1, 'Volumen')
df_merged_nuevo = df_merged_nuevo[cols]

# Eliminar las columnas de dimensiones
df_merged_nuevo = df_merged_nuevo.drop(columns=['LARGO (cm)', 'ANCHO (cm)', 'ALTO (cm)'], errors='ignore')

# Ahora normalizamos correctamente
def normalizar_descripcion(valor):
    if pd.isna(valor):
        return valor
    
    valor_str = str(valor).strip()
    
    # Primero quitamos 'EXPEDICIÓN E0'
    if valor_str.startswith('EXPEDICIÓN E0'):
        valor_str = valor_str.replace('EXPEDICIÓN E0', '', 1).strip()
    
    # Quitamos espacios y caracteres especiales al final
    valor_str = valor_str.split('/')[0].strip()  # Quita everything after /
    
    # Ahora aplicamos las reglas específicas
    if any(x in valor_str for x in ['SGE', 'EGE', 'SGP']):
        # Para SGE, EGE, SGP: deben tener 12 caracteres
        return valor_str[:12]
    elif 'M' in valor_str[:1]:  # Si comienza con M
        # Para M: deben tener 5 caracteres
        return valor_str[:5]
    else:
        # Para números u otros: dejar como está
        return valor_str

df_merged_nuevo['DESCRIPCIÓN'] = df_merged_nuevo['DESCRIPCIÓN'].apply(normalizar_descripcion)

print("Valores de DESCRIPCIÓN después de la nueva normalización:")
print("\nValores con SGE, EGE o SGP:")
sg_values = df_merged_nuevo[df_merged_nuevo['DESCRIPCIÓN'].str.contains('SGE|EGE|SGP', na=False, case=False)]['DESCRIPCIÓN'].unique()
for val in sg_values[:20]:
    print(f"'{val}' - Length: {len(val)}")

print("\nValores con M:")
m_values = df_merged_nuevo[df_merged_nuevo['DESCRIPCIÓN'].str.contains('^M', na=False, case=False, regex=True)]['DESCRIPCIÓN'].unique()
for val in m_values[:20]:
    print(f"'{val}' - Length: {len(val)}")

print("\nValores solo números:")
num_values = df_merged_nuevo[df_merged_nuevo['DESCRIPCIÓN'].str.match(r'^\d+$', na=False)]['DESCRIPCIÓN'].unique()
for val in num_values[:20]:
    print(f"'{val}' - Length: {len(val)}")

Valores de DESCRIPCIÓN después de la nueva normalización:

Valores con SGE, EGE o SGP:
'EGE02209400' - Length: 11
'EGE02210236' - Length: 11
'EGE20208245' - Length: 11
'EGE202206037' - Length: 12
'EGE202206724' - Length: 12
'EGE202206755' - Length: 12
'EGE202206764' - Length: 12
'EGE202206797' - Length: 12
'EGE202206799' - Length: 12
'EGE202206805' - Length: 12
'EGE202206806' - Length: 12
'EGE202206810' - Length: 12
'EGE202206818' - Length: 12
'EGE202206819' - Length: 12
'EGE202206820' - Length: 12
'EGE202206848' - Length: 12
'EGE202206856' - Length: 12
'EGE202206859' - Length: 12
'EGE202206872' - Length: 12
'EGE202206874' - Length: 12

Valores con M:
'M0001' - Length: 5
'M0002' - Length: 5
'M0003' - Length: 5
'M0004' - Length: 5
'M0005' - Length: 5
'M0006' - Length: 5
'M0007' - Length: 5
'M0008' - Length: 5
'M0009' - Length: 5
'M0010' - Length: 5
'M0011' - Length: 5
'M0012' - Length: 5
'M0013' - Length: 5
'M0014' - Length: 5
'M0015' - Length: 5
'M0016' - Length: 5
'M0017' - Length: 5
'M0018' - Length: 5
'M0019' - Length: 5
'M0020' - Length: 5

Valores solo números:
'100000' - Length: 6
'23' - Length: 2
'24' - Length: 2
'24375' - Length: 5
'38886' - Length: 5
'39470' - Length: 5
'40274' - Length: 5
'40277' - Length: 5
'40507' - Length: 5
'40525' - Length: 5
'40616' - Length: 5
'40625' - Length: 5
'40631' - Length: 5
'40634' - Length: 5
'40635' - Length: 5
'40650' - Length: 5
'40651' - Length: 5
'40652' - Length: 5
'40653' - Length: 5
'40654' - Length: 5

In [16]:
# Ver los valores originales de DESCRIPCIÓN que contienen EGE con 11 caracteres
print("Buscando los valores originales con EGE en df2:")
# Filtrar valores EGE de 11 caracteres del resultado actual
ege_11 = df_merged_nuevo[(df_merged_nuevo['DESCRIPCIÓN'].str.contains('EGE', na=False)) & 
                          (df_merged_nuevo['DESCRIPCIÓN'].str.len() == 11)]['DESCRIPCIÓN'].unique()
print(f"Encontrados {len(ege_11)} valores EGE con 11 caracteres en resultado")
print("Algunos ejemplos:")
for val in ege_11[:5]:
    print(f"  '{val}'")

Buscando los valores originales con EGE en df2:
Encontrados 9 valores EGE con 11 caracteres en resultado
Algunos ejemplos:
  'EGE02209400'
  'EGE02210236'
  'EGE20208245'
  'EGE20220753'
  'EGE20220894'

In [17]:
# Buscar en df2 los valores originales que generaron EGE02209400
print("Buscando en df2 los valores que pueden generar EGE02209400:")
orig_valores = df2[df2['DESCRIPCIÓN'].str.contains('02209400', na=False)]['DESCRIPCIÓN'].unique()
for val in orig_valores[:10]:
    print(f"  '{val}'")

print("\nBuscando valores que generaron EGE02210236:")
orig_valores = df2[df2['DESCRIPCIÓN'].str.contains('02210236', na=False)]['DESCRIPCIÓN'].unique()
for val in orig_valores[:10]:
    print(f"  '{val}'")

Buscando en df2 los valores que pueden generar EGE02209400:
  'EXPEDICIÓN E0EGE02209400/2022'
  'EXPEDICIÓN E0SGP202209400/2022'

Buscando valores que generaron EGE02210236:
  'EXPEDICIÓN E0EGE02210236/2022'
  'EXPEDICIÓN E0SGE202210236/2022'

In [18]:
# Normalización mejorada que maneja espacios y caracteres especiales
def normalizar_descripcion_v2(valor):
    if pd.isna(valor):
        return valor
    
    valor_str = str(valor).strip()
    
    # Quitar 'EXPEDICIÓN E0' del inicio
    if valor_str.startswith('EXPEDICIÓN E0'):
        valor_str = valor_str.replace('EXPEDICIÓN E0', '', 1).strip()
    
    # Quitar espacios (pueden estar en mitad del código)
    valor_sin_espacios = valor_str.replace(' ', '')
    
    # Quitar todo después de la barra (año)
    valor_sin_ano = valor_sin_espacios.split('/')[0].strip()
    
    # Ahora aplicar las reglas específicas
    if any(x in valor_sin_ano for x in ['SGE', 'EGE', 'SGP']):
        # Para SGE, EGE, SGP: deben tener exactamente 12 caracteres
        # Si tiene más de 12, truncar; si tiene menos de 12, dejar como está (pero lo ideal sería rellenar)
        return valor_sin_ano[:12] if len(valor_sin_ano) >= 12 else valor_sin_ano
    elif valor_sin_ano.startswith('M'):  
        # Para M: deben tener 5 caracteres
        return valor_sin_ano[:5] if len(valor_sin_ano) >= 5 else valor_sin_ano
    else:
        # Para números u otros: dejar como está
        return valor_sin_ano

# Aplicar la nueva normalización al dataframe
df_merged_nuevo['DESCRIPCIÓN'] = df_merged_nuevo['DESCRIPCIÓN'].apply(normalizar_descripcion_v2)

# Recalcular desde los datos originales con la nueva normalización
# Mantenemos df1 (Albaranes) a la LEFT y df2 (Portes) a la RIGHT para consistencia
df_merged_nuevo_v2 = pd.merge(df1, df2, on='DESCRIPCIÓN', how='left')
df_merged_nuevo_v2 = df_merged_nuevo_v2.drop(columns=columnas_a_eliminar, errors='ignore')
df_merged_nuevo_v2['Volumen'] = (df_merged_nuevo_v2['LARGO (cm)'] * df_merged_nuevo_v2['ANCHO (cm)'] * df_merged_nuevo_v2['ALTO (cm)']) / 1000000

posicion_peso = df_merged_nuevo_v2.columns.get_loc('PESO (KG)')
cols = df_merged_nuevo_v2.columns.tolist()
if 'Volumen' in cols:
    cols.remove('Volumen')
cols.insert(posicion_peso + 1, 'Volumen')
df_merged_nuevo_v2 = df_merged_nuevo_v2[cols]
df_merged_nuevo_v2 = df_merged_nuevo_v2.drop(columns=['LARGO (cm)', 'ANCHO (cm)', 'ALTO (cm)'], errors='ignore')

# Aplicar normalización
df_merged_nuevo_v2['DESCRIPCIÓN'] = df_merged_nuevo_v2['DESCRIPCIÓN'].apply(normalizar_descripcion_v2)

# Mostrar resultados
print("Valores de DESCRIPCIÓN después de la normalización mejorada:")
print("\nValores con SGE, EGE o SGP:")
sg_values = df_merged_nuevo_v2[df_merged_nuevo_v2['DESCRIPCIÓN'].str.contains('SGE|EGE|SGP', na=False, case=False)]['DESCRIPCIÓN'].unique()
for val in sg_values[:20]:
    print(f"'{val}' - Length: {len(val)}")

print("\nValores con M:")
m_values = df_merged_nuevo_v2[df_merged_nuevo_v2['DESCRIPCIÓN'].str.contains('^M', na=False, case=False, regex=True)]['DESCRIPCIÓN'].unique()
for val in m_values[:15]:
    print(f"'{val}' - Length: {len(val)}")

# Reemplazar df_merged_limpio con la versión correcta
df_merged_limpio = df_merged_nuevo_v2.copy()

Valores de DESCRIPCIÓN después de la normalización mejorada:

Valores con SGE, EGE o SGP:
'EGE02209400' - Length: 11
'EGE02210236' - Length: 11
'EGE20208245' - Length: 11
'EGE202206037' - Length: 12
'EGE202206724' - Length: 12
'EGE202206755' - Length: 12
'EGE202206764' - Length: 12
'EGE202206797' - Length: 12
'EGE202206799' - Length: 12
'EGE202206805' - Length: 12
'EGE202206806' - Length: 12
'EGE202206810' - Length: 12
'EGE202206818' - Length: 12
'EGE202206819' - Length: 12
'EGE202206820' - Length: 12
'EGE202206848' - Length: 12
'EGE202206856' - Length: 12
'EGE202206859' - Length: 12
'EGE202206872' - Length: 12
'EGE202206874' - Length: 12

Valores con M:
'M0001' - Length: 5
'M0002' - Length: 5
'M0003' - Length: 5
'M0004' - Length: 5
'M0005' - Length: 5
'M0006' - Length: 5
'M0007' - Length: 5
'M0008' - Length: 5
'M0009' - Length: 5
'M0010' - Length: 5
'M0011' - Length: 5
'M0012' - Length: 5
'M0013' - Length: 5
'M0014' - Length: 5
'M0015' - Length: 5

In [19]:
# Normalización final que rellena códigos SGE/EGE/SGP incompletos con ceros
def normalizar_descripcion_final(valor):
    if pd.isna(valor):
        return valor
    
    valor_str = str(valor).strip()
    
    # Quitar 'EXPEDICIÓN E0' del inicio
    if valor_str.startswith('EXPEDICIÓN E0'):
        valor_str = valor_str.replace('EXPEDICIÓN E0', '', 1).strip()
    
    # Quitar espacios (pueden estar en mitad del código)
    valor_sin_espacios = valor_str.replace(' ', '')
    
    # Quitar todo después de la barra (año)
    valor_sin_ano = valor_sin_espacios.split('/')[0].strip()
    
    # Ahora aplicar las reglas específicas
    if any(x in valor_sin_ano for x in ['SGE', 'EGE', 'SGP']):
        # Para SGE, EGE, SGP: deben tener exactamente 12 caracteres
        # Si tienen menos, rellenar con ceros a la derecha
        if len(valor_sin_ano) < 12:
            valor_sin_ano = valor_sin_ano.ljust(12, '0')
        return valor_sin_ano[:12]
    elif valor_sin_ano.startswith('M'):  
        # Para M: deben tener 5 caracteres
        if len(valor_sin_ano) < 5:
            valor_sin_ano = valor_sin_ano.ljust(5, '0')
        return valor_sin_ano[:5]
    else:
        # Para números u otros: dejar como está
        return valor_sin_ano

# Aplicar la normalización final
df_merged_limpio['DESCRIPCIÓN'] = df_merged_limpio['DESCRIPCIÓN'].apply(normalizar_descripcion_final)

print("Valores de DESCRIPCIÓN después de la normalización FINAL:")
print("\nValores con SGE, EGE o SGP:")
sg_values = df_merged_limpio[df_merged_limpio['DESCRIPCIÓN'].str.contains('SGE|EGE|SGP', na=False, case=False)]['DESCRIPCIÓN'].unique()
for val in sorted(sg_values):
    print(f"'{val}' - Length: {len(val)}")

print(f"\nTotal de valores SGE/EGE/SGP únicos con 12 caracteres: {(df_merged_limpio[df_merged_limpio['DESCRIPCIÓN'].str.contains('SGE|EGE|SGP', na=False, case=False)]['DESCRIPCIÓN'].str.len() == 12).sum()}")

print("\nValores con M:")
m_values = df_merged_limpio[df_merged_limpio['DESCRIPCIÓN'].str.contains('^M', na=False, case=False, regex=True)]['DESCRIPCIÓN'].unique()
for val in sorted(m_values)[:20]:
    print(f"'{val}' - Length: {len(val)}")

print(f"\nTotal de valores M únicos con 5 caracteres: {(df_merged_limpio[df_merged_limpio['DESCRIPCIÓN'].str.contains('^M', na=False, case=False, regex=True)]['DESCRIPCIÓN'].str.len() == 5).sum()}")

Valores de DESCRIPCIÓN después de la normalización FINAL:

Valores con SGE, EGE o SGP:
'EGE022094000' - Length: 12
'EGE022102360' - Length: 12
'EGE202082450' - Length: 12
'EGE202206037' - Length: 12
'EGE202206724' - Length: 12
'EGE202206755' - Length: 12
'EGE202206764' - Length: 12
'EGE202206797' - Length: 12
'EGE202206799' - Length: 12
'EGE202206805' - Length: 12
'EGE202206806' - Length: 12
'EGE202206810' - Length: 12
'EGE202206818' - Length: 12
'EGE202206819' - Length: 12
'EGE202206820' - Length: 12
'EGE202206848' - Length: 12
'EGE202206856' - Length: 12
'EGE202206859' - Length: 12
'EGE202206872' - Length: 12
'EGE202206874' - Length: 12
'EGE202206885' - Length: 12
'EGE202206892' - Length: 12
'EGE202206902' - Length: 12
'EGE202206905' - Length: 12
'EGE202206907' - Length: 12
'EGE202206922' - Length: 12
'EGE202206952' - Length: 12
'EGE202206953' - Length: 12
'EGE202206983' - Length: 12
'EGE202206987' - Length: 12
'EGE202206998' - Length: 12
'EGE202207018' - Length: 12
'EGE202207058' - Length: 12
'EGE202207064' - Length: 12
'EGE202207066' - Length: 12
'EGE202207076' - Length: 12
'EGE202207087' - Length: 12
'EGE202207089' - Length: 12
'EGE202207092' - Length: 12
'EGE202207109' - Length: 12
'EGE202207129' - Length: 12
'EGE202207138' - Length: 12
'EGE202207147' - Length: 12
'EGE202207152' - Length: 12
'EGE202207154' - Length: 12
'EGE202207155' - Length: 12
'EGE202207157' - Length: 12
'EGE202207159' - Length: 12
'EGE202207160' - Length: 12
'EGE202207164' - Length: 12
'EGE202207171' - Length: 12
'EGE202207172' - Length: 12
'EGE202207176' - Length: 12
'EGE202207177' - Length: 12
'EGE202207179' - Length: 12
'EGE202207182' - Length: 12
'EGE202207186' - Length: 12
'EGE202207192' - Length: 12
'EGE202207195' - Length: 12
'EGE202207196' - Length: 12
'EGE202207216' - Length: 12
'EGE202207217' - Length: 12
'EGE202207227' - Length: 12
'EGE202207236' - Length: 12
'EGE202207243' - Length: 12
'EGE202207245' - Length: 12
'EGE202207250' - Length: 12
'EGE202207251' - Length: 12
'EGE202207253' - Length: 12
'EGE202207261' - Length: 12
'EGE202207263' - Length: 12
'EGE202207267' - Length: 12
'EGE202207285' - Length: 12
'EGE202207299' - Length: 12
'EGE202207300' - Length: 12
'EGE202207301' - Length: 12
'EGE202207304' - Length: 12
'EGE202207306' - Length: 12
'EGE202207315' - Length: 12
'EGE202207316' - Length: 12
'EGE202207317' - Length: 12
'EGE202207324' - Length: 12
'EGE202207329' - Length: 12
'EGE202207330' - Length: 12
'EGE202207331' - Length: 12
'EGE202207349' - Length: 12
'EGE202207354' - Length: 12
'EGE202207355' - Length: 12
'EGE202207358' - Length: 12
'EGE202207360' - Length: 12
'EGE202207367' - Length: 12
'EGE202207379' - Length: 12
'EGE202207383' - Length: 12
'EGE202207390' - Length: 12
'EGE202207403' - Length: 12
'EGE202207404' - Length: 12
'EGE202207407' - Length: 12
'EGE202207415' - Length: 12
'EGE202207418' - Length: 12
'EGE202207422' - Length: 12
'EGE202207425' - Length: 12
'EGE202207426' - Length: 12
'EGE202207433' - Length: 12
'EGE202207437' - Length: 12
'EGE202207449' - Length: 12
'EGE202207467' - Length: 12
'EGE202207486' - Length: 12
'EGE202207487' - Length: 12
'EGE202207489' - Length: 12
'EGE202207492' - Length: 12
'EGE202207493' - Length: 12
'EGE202207494' - Length: 12
'EGE202207496' - Length: 12
'EGE202207499' - Length: 12
'EGE202207500' - Length: 12
'EGE202207501' - Length: 12
'EGE202207519' - Length: 12
'EGE202207522' - Length: 12
'EGE202207525' - Length: 12
'EGE202207526' - Length: 12
'EGE202207527' - Length: 12
'EGE202207528' - Length: 12
'EGE202207529' - Length: 12
'EGE202207530' - Length: 12
'EGE202207534' - Length: 12
'EGE202207538' - Length: 12
'EGE202207539' - Length: 12
'EGE202207542' - Length: 12
'EGE202207550' - Length: 12
'EGE202207554' - Length: 12
'EGE202207555' - Length: 12
'EGE202207558' - Length: 12
'EGE202207559' - Length: 12
'EGE202207560' - Length: 12
'EGE202207561' - Length: 12
'EGE202207564' - Length: 12
'EGE202207565' - Length: 12
'EGE202207578' - Length: 12
'EGE202207584' - Length: 12
'EGE202207588' - Length: 12
'EGE202207589' - Length: 12
'EGE202207592' - Length: 12
'EGE202207593' - Length: 12
'EGE202207600' - Length: 12
'EGE202207601' - Length: 12
'EGE202207602' - Length: 12
'EGE202207604' - Length: 12
'EGE202207605' - Length: 12
'EGE202207614' - Length: 12
'EGE202207621' - Length: 12
'EGE202207626' - Length: 12
'EGE202207631' - Length: 12
'EGE202207633' - Length: 12
'EGE202207636' - Length: 12
'EGE202207641' - Length: 12
'EGE202207642' - Length: 12
'EGE202207645' - Length: 12
'EGE202207651' - Length: 12
'EGE202207653' - Length: 12
'EGE202207655' - Length: 12
'EGE202207656' - Length: 12
'EGE202207658' - Length: 12
'EGE202207660' - Length: 12
'EGE202207661' - Length: 12
'EGE202207679' - Length: 12
'EGE202207681' - Length: 12
'EGE202207693' - Length: 12
'EGE202207695' - Length: 12
'EGE202207697' - Length: 12
'EGE202207702' - Length: 12
'EGE202207703' - Length: 12
'EGE202207704' - Length: 12
'EGE202207707' - Length: 12
'EGE202207708' - Length: 12
'EGE202207714' - Length: 12
'EGE202207716' - Length: 12
'EGE202207717' - Length: 12
'EGE202207721' - Length: 12
'EGE202207724' - Length: 12
'EGE202207729' - Length: 12
'EGE202207731' - Length: 12
'EGE202207732' - Length: 12
'EGE202207733' - Length: 12
'EGE202207737' - Length: 12
'EGE202207745' - Length: 12
'EGE202207749' - Length: 12
'EGE202207750' - Length: 12
'EGE202207751' - Length: 12
'EGE202207758' - Length: 12
'EGE202207763' - Length: 12
'EGE202207774' - Length: 12
'EGE202207782' - Length: 12
'EGE202207784' - Length: 12
'EGE202207790' - Length: 12
'EGE202207795' - Length: 12
'EGE202207796' - Length: 12
'EGE202207817' - Length: 12
'EGE202207819' - Length: 12
'EGE202207820' - Length: 12
'EGE202207821' - Length: 12
'EGE202207822' - Length: 12
'EGE202207824' - Length: 12
'EGE202207838' - Length: 12
'EGE202207839' - Length: 12
'EGE202207842' - Length: 12
'EGE202207845' - Length: 12
'EGE202207846' - Length: 12
'EGE202207854' - Length: 12
'EGE202207858' - Length: 12
'EGE202207870' - Length: 12
'EGE202207878' - Length: 12
'EGE202207880' - Length: 12
'EGE202207882' - Length: 12
'EGE202207885' - Length: 12
'EGE202207886' - Length: 12
'EGE202207887' - Length: 12
'EGE202207888' - Length: 12
'EGE202207890' - Length: 12
'EGE202207893' - Length: 12
'EGE202207894' - Length: 12
'EGE202207896' - Length: 12
'EGE202207910' - Length: 12
'EGE202207911' - Length: 12
'EGE202207912' - Length: 12
'EGE202207913' - Length: 12
'EGE202207916' - Length: 12
'EGE202207917' - Length: 12
'EGE202207920' - Length: 12
'EGE202207922' - Length: 12
'EGE202207925' - Length: 12
'EGE202207927' - Length: 12
'EGE202207937' - Length: 12
'EGE202207939' - Length: 12
'EGE202207955' - Length: 12
'EGE202207957' - Length: 12
'EGE202207964' - Length: 12
'EGE202207968' - Length: 12
'EGE202207969' - Length: 12
'EGE202207977' - Length: 12
'EGE202207982' - Length: 12
'EGE202207987' - Length: 12
'EGE202207993' - Length: 12
'EGE202208010' - Length: 12
'EGE202208017' - Length: 12
'EGE202208027' - Length: 12
'EGE202208041' - Length: 12
'EGE202208042' - Length: 12
'EGE202208059' - Length: 12
'EGE202208065' - Length: 12
'EGE202208066' - Length: 12
'EGE202208075' - Length: 12
'EGE202208076' - Length: 12
'EGE202208081' - Length: 12
'EGE202208082' - Length: 12
'EGE202208083' - Length: 12
'EGE202208086' - Length: 12
'EGE202208087' - Length: 12
'EGE202208088' - Length: 12
'EGE202208091' - Length: 12
'EGE202208092' - Length: 12
'EGE202208102' - Length: 12
'EGE202208104' - Length: 12
'EGE202208107' - Length: 12
'EGE202208114' - Length: 12
'EGE202208118' - Length: 12
'EGE202208120' - Length: 12
'EGE202208127' - Length: 12
'EGE202208129' - Length: 12
'EGE202208132' - Length: 12
'EGE202208133' - Length: 12
'EGE202208148' - Length: 12
'EGE202208161' - Length: 12
'EGE202208177' - Length: 12
'EGE202208195' - Length: 12
'EGE202208200' - Length: 12
'EGE202208212' - Length: 12
'EGE202208216' - Length: 12
'EGE202208219' - Length: 12
'EGE202208233' - Length: 12
'EGE202208244' - Length: 12
'EGE202208275' - Length: 12
'EGE202208290' - Length: 12
'EGE202208291' - Length: 12
'EGE202208292' - Length: 12
'EGE202208293' - Length: 12
'EGE202208296' - Length: 12
'EGE202208348' - Length: 12
'EGE202208350' - Length: 12
'EGE202208352' - Length: 12
'EGE202208355' - Length: 12
'EGE202208397' - Length: 12
'EGE202208418' - Length: 12
'EGE202208420' - Length: 12
'EGE202208426' - Length: 12
'EGE202208459' - Length: 12
'EGE202208482' - Length: 12
'EGE202208523' - Length: 12
'EGE202208528' - Length: 12
'EGE202208530' - Length: 12
'EGE202208531' - Length: 12
'EGE202208534' - Length: 12
'EGE202208564' - Length: 12
'EGE202208567' - Length: 12
'EGE202208582' - Length: 12
'EGE202208610' - Length: 12
'EGE202208611' - Length: 12
'EGE202208621' - Length: 12
'EGE202208622' - Length: 12
'EGE202208623' - Length: 12
'EGE202208633' - Length: 12
'EGE202208647' - Length: 12
'EGE202208685' - Length: 12
'EGE202208686' - Length: 12
'EGE202208698' - Length: 12
'EGE202208699' - Length: 12
'EGE202208714' - Length: 12
'EGE202208719' - Length: 12
'EGE202208720' - Length: 12
'EGE202208721' - Length: 12
'EGE202208725' - Length: 12
'EGE202208726' - Length: 12
'EGE202208727' - Length: 12
'EGE202208729' - Length: 12
'EGE202208767' - Length: 12
'EGE202208768' - Length: 12
'EGE202208772' - Length: 12
'EGE202208774' - Length: 12
'EGE202208780' - Length: 12
'EGE202208801' - Length: 12
'EGE202208802' - Length: 12
'EGE202208804' - Length: 12
'EGE202208805' - Length: 12
'EGE202208806' - Length: 12
'EGE202208822' - Length: 12
'EGE202208824' - Length: 12
'EGE202208825' - Length: 12
'EGE202208829' - Length: 12
'EGE202208837' - Length: 12
'EGE202208838' - Length: 12
'EGE202208841' - Length: 12
'EGE202208869' - Length: 12
'EGE202208870' - Length: 12
'EGE202208871' - Length: 12
'EGE202208872' - Length: 12
'EGE202208879' - Length: 12
'EGE202208880' - Length: 12
'EGE202208881' - Length: 12
'EGE202208892' - Length: 12
'EGE202208893' - Length: 12
'EGE202208895' - Length: 12
'EGE202208897' - Length: 12
'EGE202208898' - Length: 12
'EGE202208906' - Length: 12
'EGE202208910' - Length: 12
'EGE202208912' - Length: 12
'EGE202208919' - Length: 12
'EGE202208920' - Length: 12
'EGE202208922' - Length: 12
'EGE202208930' - Length: 12
'EGE202208940' - Length: 12
'EGE202208941' - Length: 12
'EGE202208942' - Length: 12
'EGE202208943' - Length: 12
'EGE202208948' - Length: 12
'EGE202208959' - Length: 12
'EGE202208963' - Length: 12
'EGE202208964' - Length: 12
'EGE202208965' - Length: 12
'EGE202208974' - Length: 12
'EGE202208975' - Length: 12
'EGE202208991' - Length: 12
'EGE202208992' - Length: 12
'EGE202208993' - Length: 12
'EGE202209006' - Length: 12
'EGE202209008' - Length: 12
'EGE202209011' - Length: 12
'EGE202209012' - Length: 12
'EGE202209013' - Length: 12
'EGE202209029' - Length: 12
'EGE202209035' - Length: 12
'EGE202209047' - Length: 12
'EGE202209050' - Length: 12
'EGE202209052' - Length: 12
'EGE202209083' - Length: 12
'EGE202209113' - Length: 12
'EGE202209122' - Length: 12
'EGE202209126' - Length: 12
'EGE202209132' - Length: 12
'EGE202209133' - Length: 12
'EGE202209135' - Length: 12
'EGE202209136' - Length: 12
'EGE202209140' - Length: 12
'EGE202209147' - Length: 12
'EGE202209148' - Length: 12
'EGE202209165' - Length: 12
'EGE202209167' - Length: 12
'EGE202209172' - Length: 12
'EGE202209180' - Length: 12
'EGE202209183' - Length: 12
'EGE202209188' - Length: 12
'EGE202209192' - Length: 12
'EGE202209202' - Length: 12
'EGE202209209' - Length: 12
'EGE202209211' - Length: 12
'EGE202209212' - Length: 12
'EGE202209214' - Length: 12
'EGE202209215' - Length: 12
'EGE202209218' - Length: 12
'EGE202209221' - Length: 12
'EGE202209228' - Length: 12
'EGE202209229' - Length: 12
'EGE202209232' - Length: 12
'EGE202209235' - Length: 12
'EGE202209239' - Length: 12
'EGE202209242' - Length: 12
'EGE202209245' - Length: 12
'EGE202209249' - Length: 12
'EGE202209255' - Length: 12
'EGE202209256' - Length: 12
'EGE202209261' - Length: 12
'EGE202209267' - Length: 12
'EGE202209270' - Length: 12
'EGE202209271' - Length: 12
'EGE202209272' - Length: 12
'EGE202209281' - Length: 12
'EGE202209282' - Length: 12
'EGE202209283' - Length: 12
'EGE202209285' - Length: 12
'EGE202209292' - Length: 12
'EGE202209300' - Length: 12
'EGE202209301' - Length: 12
'EGE202209303' - Length: 12
'EGE202209311' - Length: 12
'EGE202209313' - Length: 12
'EGE202209314' - Length: 12
'EGE202209317' - Length: 12
'EGE202209325' - Length: 12
'EGE202209326' - Length: 12
'EGE202209328' - Length: 12
'EGE202209330' - Length: 12
'EGE202209335' - Length: 12
'EGE202209336' - Length: 12
'EGE202209346' - Length: 12
'EGE202209347' - Length: 12
'EGE202209359' - Length: 12
'EGE202209364' - Length: 12
'EGE202209366' - Length: 12
'EGE202209367' - Length: 12
'EGE202209373' - Length: 12
'EGE202209380' - Length: 12
'EGE202209381' - Length: 12
'EGE202209383' - Length: 12
'EGE202209384' - Length: 12
'EGE202209403' - Length: 12
'EGE202209407' - Length: 12
'EGE202209413' - Length: 12
'EGE202209417' - Length: 12
'EGE202209420' - Length: 12
'EGE202209422' - Length: 12
'EGE202209427' - Length: 12
'EGE202209429' - Length: 12
'EGE202209432' - Length: 12
'EGE202209433' - Length: 12
'EGE202209434' - Length: 12
'EGE202209453' - Length: 12
'EGE202209461' - Length: 12
'EGE202209464' - Length: 12
'EGE202209479' - Length: 12
'EGE202209480' - Length: 12
'EGE202209481' - Length: 12
'EGE202209485' - Length: 12
'EGE202209488' - Length: 12
'EGE202209490' - Length: 12
'EGE202209491' - Length: 12
'EGE202209492' - Length: 12
'EGE202209493' - Length: 12
'EGE202209508' - Length: 12
'EGE202209517' - Length: 12
'EGE202209526' - Length: 12
'EGE202209543' - Length: 12
'EGE202209548' - Length: 12
'EGE202209549' - Length: 12
'EGE202209553' - Length: 12
'EGE202209558' - Length: 12
'EGE202209560' - Length: 12
'EGE202209582' - Length: 12
'EGE202209592' - Length: 12
'EGE202209599' - Length: 12
'EGE202209605' - Length: 12
'EGE202209607' - Length: 12
'EGE202209615' - Length: 12
'EGE202209617' - Length: 12
'EGE202209626' - Length: 12
'EGE202209668' - Length: 12
'EGE202209669' - Length: 12
'EGE202209677' - Length: 12
'EGE202209678' - Length: 12
'EGE202209692' - Length: 12
'EGE202209706' - Length: 12
'EGE202209707' - Length: 12
'EGE202209709' - Length: 12
'EGE202209711' - Length: 12
'EGE202209712' - Length: 12
'EGE202209716' - Length: 12
'EGE202209736' - Length: 12
'EGE202209741' - Length: 12
'EGE202209761' - Length: 12
'EGE202209797' - Length: 12
'EGE202209799' - Length: 12
'EGE202209807' - Length: 12
'EGE202209810' - Length: 12
'EGE202209811' - Length: 12
'EGE202209812' - Length: 12
'EGE202209813' - Length: 12
'EGE202209815' - Length: 12
'EGE202209823' - Length: 12
'EGE202209834' - Length: 12
'EGE202209835' - Length: 12
'EGE202209839' - Length: 12
'EGE202209849' - Length: 12
'EGE202209852' - Length: 12
'EGE202209853' - Length: 12
'EGE202209867' - Length: 12
'EGE202209872' - Length: 12
'EGE202209874' - Length: 12
'EGE202209887' - Length: 12
'EGE202209888' - Length: 12
'EGE202209890' - Length: 12
'EGE202209901' - Length: 12
'EGE202209903' - Length: 12
'EGE202209920' - Length: 12
'EGE202209921' - Length: 12
'EGE202209922' - Length: 12
'EGE202209932' - Length: 12
'EGE202209934' - Length: 12
'EGE202209939' - Length: 12
'EGE202209942' - Length: 12
'EGE202209953' - Length: 12
'EGE202209955' - Length: 12
'EGE202209956' - Length: 12
'EGE202209963' - Length: 12
'EGE202209965' - Length: 12
'EGE202209966' - Length: 12
'EGE202209967' - Length: 12
'EGE202209969' - Length: 12
'EGE202209971' - Length: 12
'EGE202209977' - Length: 12
'EGE202209984' - Length: 12
'EGE202209985' - Length: 12
'EGE202209987' - Length: 12
'EGE202209988' - Length: 12
'EGE202209989' - Length: 12
'EGE202209990' - Length: 12
'EGE202209997' - Length: 12
'EGE202209998' - Length: 12
'EGE202210010' - Length: 12
'EGE202210016' - Length: 12
'EGE202210019' - Length: 12
'EGE202210075' - Length: 12
'EGE202210081' - Length: 12
'EGE202210082' - Length: 12
'EGE202210093' - Length: 12
'EGE202210099' - Length: 12
'EGE202210125' - Length: 12
'EGE202210129' - Length: 12
'EGE202210130' - Length: 12
'EGE202210138' - Length: 12
'EGE202210149' - Length: 12
'EGE202210150' - Length: 12
'EGE202210152' - Length: 12
'EGE202210154' - Length: 12
'EGE202210160' - Length: 12
'EGE202210161' - Length: 12
'EGE202210164' - Length: 12
'EGE202210165' - Length: 12
'EGE202210172' - Length: 12
'EGE202210173' - Length: 12
'EGE202210174' - Length: 12
'EGE202210181' - Length: 12
'EGE202210182' - Length: 12
'EGE202210186' - Length: 12
'EGE202210190' - Length: 12
'EGE202210202' - Length: 12
'EGE202210207' - Length: 12
'EGE202210211' - Length: 12
'EGE202210214' - Length: 12
'EGE202210222' - Length: 12
'EGE202210223' - Length: 12
'EGE202210224' - Length: 12
'EGE202210225' - Length: 12
'EGE202210228' - Length: 12
'EGE202210230' - Length: 12
'EGE202210231' - Length: 12
'EGE202210233' - Length: 12
'EGE202210247' - Length: 12
'EGE202210253' - Length: 12
'EGE202210261' - Length: 12
'EGE202210268' - Length: 12
'EGE202210270' - Length: 12
'EGE202210273' - Length: 12
'EGE202210286' - Length: 12
'EGE202210291' - Length: 12
'EGE202210295' - Length: 12
'EGE202210297' - Length: 12
'EGE202210308' - Length: 12
'EGE202210309' - Length: 12
'EGE202210314' - Length: 12
'EGE202210322' - Length: 12
'EGE202210323' - Length: 12
'EGE202210326' - Length: 12
'EGE202210328' - Length: 12
'EGE202210329' - Length: 12
'EGE202210346' - Length: 12
'EGE202210357' - Length: 12
'EGE202210364' - Length: 12
'EGE202210365' - Length: 12
'EGE202210366' - Length: 12
'EGE202210369' - Length: 12
'EGE202210384' - Length: 12
'EGE202210387' - Length: 12
'EGE202210391' - Length: 12
'EGE202210397' - Length: 12
'EGE202210428' - Length: 12
'EGE202210431' - Length: 12
'EGE202210433' - Length: 12
'EGE202210434' - Length: 12
'EGE202210435' - Length: 12
'EGE202210446' - Length: 12
'EGE202210449' - Length: 12
'EGE202210454' - Length: 12
'EGE202210455' - Length: 12
'EGE202210467' - Length: 12
'EGE202210470' - Length: 12
'EGE202210477' - Length: 12
'EGE202210479' - Length: 12
'EGE202210480' - Length: 12
'EGE202210482' - Length: 12
'EGE202210485' - Length: 12
'EGE202210487' - Length: 12
'EGE202210489' - Length: 12
'EGE202210498' - Length: 12
'EGE202210500' - Length: 12
'EGE202210503' - Length: 12
'EGE202210505' - Length: 12
'EGE202210511' - Length: 12
'EGE202210512' - Length: 12
'EGE202210513' - Length: 12
'EGE202210515' - Length: 12
'EGE202210535' - Length: 12
'EGE202210543' - Length: 12
'EGE202210547' - Length: 12
'EGE202210552' - Length: 12
'EGE202210583' - Length: 12
'EGE202210588' - Length: 12
'EGE202210596' - Length: 12
'EGE202210610' - Length: 12
'EGE202210622' - Length: 12
'EGE202210631' - Length: 12
'EGE202210633' - Length: 12
'EGE202210650' - Length: 12
'EGE202210673' - Length: 12
'EGE202210682' - Length: 12
'EGE202210685' - Length: 12
'EGE202210686' - Length: 12
'EGE202210708' - Length: 12
'EGE202210729' - Length: 12
'EGE202210740' - Length: 12
'EGE202210742' - Length: 12
'EGE202210763' - Length: 12
'EGE202210766' - Length: 12
'EGE202210997' - Length: 12
'EGE202310702' - Length: 12
'EGE202310794' - Length: 12
'EGE202310918' - Length: 12
'EGE202310959' - Length: 12
'EGE202310970' - Length: 12
'EGE202311064' - Length: 12
'EGE202311073' - Length: 12
'EGE202311077' - Length: 12
'EGE202311079' - Length: 12
'EGE202311080' - Length: 12
'EGE202311081' - Length: 12
'EGE202311082' - Length: 12
'EGE202311092' - Length: 12
'EGE202311093' - Length: 12
'EGE202311095' - Length: 12
'EGE202311096' - Length: 12
'EGE202311104' - Length: 12
'EGE202311105' - Length: 12
'EGE202311118' - Length: 12
'EGE202311120' - Length: 12
'EGE202311128' - Length: 12
'EGE202311172' - Length: 12
'EGE202311217' - Length: 12
'EGE202311222' - Length: 12
'EGE202311227' - Length: 12
'EGE202311228' - Length: 12
'EGE202311237' - Length: 12
'EGE202311240' - Length: 12
'EGE202311243' - Length: 12
'EGE202311255' - Length: 12
'EGE202311304' - Length: 12
'EGE202311305' - Length: 12
'EGE202311308' - Length: 12
'EGE202311309' - Length: 12
'EGE202311310' - Length: 12
'EGE202311341' - Length: 12
'EGE202311342' - Length: 12
'EGE202311350' - Length: 12
'EGE202311356' - Length: 12
'EGE202311362' - Length: 12

In [20]:
# Verificar la normalización
print("RESUMEN DE NORMALIZACIÓN:")
print("="*60)

# SGE/EGE/SGP
sg_mask = df_merged_limpio['DESCRIPCIÓN'].str.contains('SGE|EGE|SGP', na=False, case=False)
sg_len_12 = (df_merged_limpio[sg_mask]['DESCRIPCIÓN'].str.len() == 12).sum()
sg_total = sg_mask.sum()
print(f"\nSGE/EGE/SGP: {sg_len_12}/{sg_total} valores con exactamente 12 caracteres")
print("Ejemplos:")
for val in df_merged_limpio[sg_mask]['DESCRIPCIÓN'].unique()[:10]:
    print(f"  '{val}' (length: {len(val)})")

# M
m_mask = df_merged_limpio['DESCRIPCIÓN'].str.contains('^M', na=False, case=False, regex=True)
m_len_5 = (df_merged_limpio[m_mask]['DESCRIPCIÓN'].str.len() == 5).sum()
m_total = m_mask.sum()
print(f"\nM: {m_len_5}/{m_total} valores con exactamente 5 caracteres")
print("Ejemplos:")
for val in sorted(df_merged_limpio[m_mask]['DESCRIPCIÓN'].unique()[:10]):
    print(f"  '{val}' (length: {len(val)})")

# Números
num_mask = df_merged_limpio['DESCRIPCIÓN'].str.match(r'^\d+$', na=False)
num_total = num_mask.sum()
print(f"\nNúmeros: {num_total} valores (sin cambios en la estructura)")
print("Ejemplos:")
for val in sorted(df_merged_limpio[num_mask]['DESCRIPCIÓN'].unique()[:10]):
    print(f"  '{val}' (length: {len(val)})")

RESUMEN DE NORMALIZACIÓN:
============================================================

SGE/EGE/SGP: 16219/16219 valores con exactamente 12 caracteres
Ejemplos:
  'EGE022094000' (length: 12)
  'EGE022102360' (length: 12)
  'EGE202082450' (length: 12)
  'EGE202206037' (length: 12)
  'EGE202206724' (length: 12)
  'EGE202206755' (length: 12)
  'EGE202206764' (length: 12)
  'EGE202206797' (length: 12)
  'EGE202206799' (length: 12)
  'EGE202206805' (length: 12)

M: 5073/5073 valores con exactamente 5 caracteres
Ejemplos:
  'M0001' (length: 5)
  'M0002' (length: 5)
  'M0003' (length: 5)
  'M0004' (length: 5)
  'M0005' (length: 5)
  'M0006' (length: 5)
  'M0007' (length: 5)
  'M0008' (length: 5)
  'M0009' (length: 5)
  'M0010' (length: 5)

Números: 539 valores (sin cambios en la estructura)
Ejemplos:
  '100000' (length: 6)
  '23' (length: 2)
  '24' (length: 2)
  '24375' (length: 5)
  '38886' (length: 5)
  '39470' (length: 5)
  '40274' (length: 5)
  '40277' (length: 5)
  '40507' (length: 5)
  '40525' (length: 5)

In [21]:
print("\nDataframe final con la DESCRIPCIÓN normalizada:")
df_merged_limpio

Dataframe final con la DESCRIPCIÓN normalizada:

,ITEM,FECHA SERVICIO,CONCEPTO (DENOMINACIÓN EVENTO ASOCIADO),DESCRIPCIÓN,SOLICITANTE MAHOU,DPTO MAHOU,PALÉS IN,CAJAS IN,M3 IN,PALÉS OUT,...,NOCHES DESPLAZAM X OPERARIO,CP,URGENCIA,FESTIVO,PROVINCIA DESTINO,TIEMPO RELOJ TRANSPORTE (HORAS),TIEMPO RELOJ CARGA Y DESCARGA (HORAS),Nº OPERARIOS (SIN CONTAR CHÓFER),PESO (KG),Volumen
0,35372.0,NaT,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,32145.0,NaT,NaN,100000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,34186.0,2023-05-01,PORTE ENVIO PRODUCTO GANADOR PAULA LOPEZ JIMEN...,23,BEATRIZ DONOSO,MAHOU,NaN,NaN,NaN,NaN,...,NaN,30165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,34185.0,2023-04-03,PORTE ENVIO PRODUCTO GANADOR PAULA LOPEZ JIMEN...,24,BEATRIZ DONOSO,MAHOU,NaN,NaN,NaN,NaN,...,NaN,30165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,30235.0,2022-01-18,PORTE ENTREGA MOSTRADOR FITUR STAND ALCALA DE ...,24375,ALBA GARCIA,DCMC – Madrid,NaN,NaN,NaN,NaN,...,NaN,28042,NO,NO,Madrid,1.0,0.7,1.0,140.0,1.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23548,52637.0,2024-12-30,PORTE ENVIO URGENTE GPI,SGP202523811,GIULIA ARNOLS,RODAJE 5 ESTRELLAS,NaN,NaN,NaN,1.0,...,NaN,8711,NO,NO,Barcelona,0.0,0.0,0.0,180.0,0.40
23549,52633.0,2024-12-30,PORTE ENTREGA URGENTE SAICA,SGP202523812,GIULIA ARNOLS,RODAJE 5 ESTRELLAS,NaN,NaN,NaN,1.0,...,NaN,28108,NO,NO,Madrid,1.0,0.7,0.0,180.0,0.40
23550,52634.0,2024-12-30,PORTE ENTREGA URGENTE NEW BOX,SGP202523815,GIULIA ARNOLS,RODAJE 5 ESTRELLAS,NaN,NaN,NaN,1.0,...,NaN,28025,NO,NO,Madrid,1.0,0.7,1.0,180.0,0.40
23551,52640.0,2025-01-03,PORTE ENTREGA GRIFO ECESA,SGP202523817,BEATRIZ DONOSO,MAHOU,NaN,NaN,NaN,NaN,...,NaN,28906,NO,NO,Madrid,1.0,0.3,0.0,15.0,0.04
23552,52653.0,2025-03-18,EXPEDICION BOTELLERO BETO TORRES Y CARRERA,SGP202523821,JESUS MANUEL SAEZ,MAHOU GALICIA Y ASTURIAS,NaN,NaN,NaN,NaN,...,NaN,36416 - PONTEVEDRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
# Crear columna 'CAJAS OUT' a partir de 'CAJAS SIN MANIPULACIÓN' y 'CAJAS CON MANIPULACIÓN'
def _cajas_out(a, b):
    if pd.isna(a) and pd.isna(b):
        return pd.NA
    if pd.isna(a):
        return b
    if pd.isna(b):
        return a
    # ambas presentes
    return a if a == b else (a if a > b else b)

df_merged_limpio['CAJAS OUT'] = df_merged_limpio['CAJAS SIN MANIPULACIÓN'].combine(
    df_merged_limpio['CAJAS CON MANIPULACIÓN'], _cajas_out)

# Convertir a numérico cuando sea posible
df_merged_limpio['CAJAS OUT'] = pd.to_numeric(df_merged_limpio['CAJAS OUT'], errors='coerce')

# Eliminar las columnas originales
df_merged_limpio = df_merged_limpio.drop(columns=['CAJAS SIN MANIPULACIÓN', 'CAJAS CON MANIPULACIÓN'], errors='ignore')

# Mostrar comprobación
df_merged_limpio[['CAJAS OUT']].head()

   CAJAS OUT
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN

In [23]:
df_merged_limpio

,ITEM,FECHA SERVICIO,CONCEPTO (DENOMINACIÓN EVENTO ASOCIADO),DESCRIPCIÓN,SOLICITANTE MAHOU,DPTO MAHOU,PALÉS IN,CAJAS IN,M3 IN,PALÉS OUT,...,CP,URGENCIA,FESTIVO,PROVINCIA DESTINO,TIEMPO RELOJ TRANSPORTE (HORAS),TIEMPO RELOJ CARGA Y DESCARGA (HORAS),Nº OPERARIOS (SIN CONTAR CHÓFER),PESO (KG),Volumen,CAJAS OUT
0,35372.0,NaT,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,32145.0,NaT,NaN,100000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,34186.0,2023-05-01,PORTE ENVIO PRODUCTO GANADOR PAULA LOPEZ JIMEN...,23,BEATRIZ DONOSO,MAHOU,NaN,NaN,NaN,NaN,...,30165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,34185.0,2023-04-03,PORTE ENVIO PRODUCTO GANADOR PAULA LOPEZ JIMEN...,24,BEATRIZ DONOSO,MAHOU,NaN,NaN,NaN,NaN,...,30165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,30235.0,2022-01-18,PORTE ENTREGA MOSTRADOR FITUR STAND ALCALA DE ...,24375,ALBA GARCIA,DCMC – Madrid,NaN,NaN,NaN,NaN,...,28042,NO,NO,Madrid,1.0,0.7,1.0,140.0,1.50,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23548,52637.0,2024-12-30,PORTE ENVIO URGENTE GPI,SGP202523811,GIULIA ARNOLS,RODAJE 5 ESTRELLAS,NaN,NaN,NaN,1.0,...,8711,NO,NO,Barcelona,0.0,0.0,0.0,180.0,0.40,NaN
23549,52633.0,2024-12-30,PORTE ENTREGA URGENTE SAICA,SGP202523812,GIULIA ARNOLS,RODAJE 5 ESTRELLAS,NaN,NaN,NaN,1.0,...,28108,NO,NO,Madrid,1.0,0.7,0.0,180.0,0.40,NaN
23550,52634.0,2024-12-30,PORTE ENTREGA URGENTE NEW BOX,SGP202523815,GIULIA ARNOLS,RODAJE 5 ESTRELLAS,NaN,NaN,NaN,1.0,...,28025,NO,NO,Madrid,1.0,0.7,1.0,180.0,0.40,NaN
23551,52640.0,2025-01-03,PORTE ENTREGA GRIFO ECESA,SGP202523817,BEATRIZ DONOSO,MAHOU,NaN,NaN,NaN,NaN,...,28906,NO,NO,Madrid,1.0,0.3,0.0,15.0,0.04,1.0
23552,52653.0,2025-03-18,EXPEDICION BOTELLERO BETO TORRES Y CARRERA,SGP202523821,JESUS MANUEL SAEZ,MAHOU GALICIA Y ASTURIAS,NaN,NaN,NaN,NaN,...,36416 - PONTEVEDRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
# Analizar valores que empiezan con "OCUPAC"
print("ANÁLISIS DE VALORES 'OCUPAC'")
print("="*80)

# Buscar en el dataframe final
ocupac_mask = df_merged_limpio['DESCRIPCIÓN'].str.startswith('OCUPAC', na=False)
ocupac_values = df_merged_limpio[ocupac_mask]['DESCRIPCIÓN'].unique()
ocupac_count = ocupac_mask.sum()

print(f"\n✓ Encontrados {ocupac_count} filas con 'OCUPAC' en df_merged_limpio")
print(f"✓ Valores únicos: {len(ocupac_values)}")

if len(ocupac_values) > 0:
    print("\nEjemplos de valores 'OCUPAC':")
    for val in ocupac_values[:10]:
        print(f"  '{val}'")
else:
    print("\nNo hay valores 'OCUPAC' en el resultado final")

# Buscar en df1 original (Albaranes)
print("\n" + "="*80)
print("\nBuscando en df1 (Albaranes) original:")
ocupac_df1 = df1[df1['DESCRIPCIÓN'].str.contains('OCUPAC', na=False, case=False)]
print(f"Encontrados {len(ocupac_df1)} filas con 'OCUPAC' en df1")

if len(ocupac_df1) > 0:
    print("Valores únicos en df1:")
    for val in ocupac_df1['DESCRIPCIÓN'].unique()[:10]:
        print(f"  '{val}'")

ANÁLISIS DE VALORES 'OCUPAC'
================================================================================

✓ Encontrados 1467 filas con 'OCUPAC' en df_merged_limpio
✓ Valores únicos: 1442

Ejemplos de valores 'OCUPAC':
  'OCUPACIÓNMEDIAALHAMBRA-IRISDELPALACIOAGOSTO2022'
  'OCUPACIÓNMEDIAALHAMBRA-IRISDELPALACIODICIEMBRE2022'
  'OCUPACIÓNMEDIAALHAMBRA-IRISDELPALACIOJULIO2022'
  'OCUPACIÓNMEDIAALHAMBRA-IRISDELPALACIONOVIEMBRE2022'
  'OCUPACIÓNMEDIAALHAMBRA-IRISDELPALACIOOCTUBRE2022'
  'OCUPACIÓNMEDIAALHAMBRA-IRISDELPALACIOSEPTIEMBRE2022'
  'OCUPACIONMEDIAALHAMBRA-MARIAAMIGODICIEMBRE2022'
  'OCUPACIONMEDIAALHAMBRA-MARIAAMIGONOVIEMBRE2022'
  'OCUPACIONMEDIAALHAMBRA-MARIAAMIGOOCTUBRE2022'
  'OCUPACIÓNMEDIAALHAMBRAABRIL2022'

================================================================================

Buscando en df1 (Albaranes) original:
Encontrados 1561 filas con 'OCUPAC' en df1
Valores únicos en df1:
  'EXPEDICIÓN E0OCUPACIÓN MEDIA ALHAMBRA - IRIS DEL PALACIO AGOSTO 2022/2022'
  'EXPEDICIÓN E0OCUPACIÓN MEDIA ALHAMBRA - IRIS DEL PALACIO DICIEMBRE 2022/2022'
  'EXPEDICIÓN E0OCUPACIÓN MEDIA ALHAMBRA - IRIS DEL PALACIO JULIO 2022/2022'
  'EXPEDICIÓN E0OCUPACIÓN MEDIA ALHAMBRA - IRIS DEL PALACIO NOVIEMBRE 2022/2022'
  'EXPEDICIÓN E0OCUPACIÓN MEDIA ALHAMBRA - IRIS DEL PALACIO OCTUBRE 2022/2022'
  'EXPEDICIÓN E0OCUPACIÓN MEDIA ALHAMBRA - IRIS DEL PALACIO SEPTIEMBRE 2022/2022'
  'EXPEDICIÓN E0OCUPACION MEDIA ALHAMBRA - MARIA AMIGO DICIEMBRE 2022/2022'
  'EXPEDICIÓN E0OCUPACION MEDIA ALHAMBRA - MARIA AMIGO NOVIEMBRE 2022/2022'
  'EXPEDICIÓN E0OCUPACION MEDIA ALHAMBRA - MARIA AMIGO OCTUBRE 2022/2022'
  'EXPEDICIÓN E0OCUPACIÓN MEDIA ALHAMBRA ABRIL 2022/2022'

In [26]:
# Verificar si estos valores OCUPAC están en df2 (Portes)
print("\n" + "="*80)
print("\nBuscando 'OCUPAC' en df2 (Portes):")
ocupac_df2 = df2[df2['DESCRIPCIÓN'].str.contains('OCUPAC', na=False, case=False)]
print(f"Encontrados {len(ocupac_df2)} filas con 'OCUPAC' en df2")

if len(ocupac_df2) > 0:
    print("Valores en df2:")
    for val in ocupac_df2['DESCRIPCIÓN'].unique()[:5]:
        print(f"  '{val}'")
else:
    print("→ NO hay valores 'OCUPAC' en df2 (Portes)")

# Verificar qué filas del resultado tienen OCUPAC
print("\n" + "="*80)
print("\nAnálisis de las filas OCUPAC en el resultado final:")

ocupac_resultado = df_merged_limpio[ocupac_mask]
print(f"\nTotal de filas OCUPAC: {len(ocupac_resultado)}")

# Verificar si tienen datos de Portes (columnas de Portes rellenadas)
portes_cols = ['URGENCIA', 'FESTIVO', 'PROVINCIA DESTINO', 'TIEMPO RELOJ TRANSPORTE (HORAS)', 
               'TIEMPO RELOJ CARGA Y DESCARGA (HORAS)', 'Nº OPERARIOS (SIN CONTAR CHÓFER)']

print(f"\nVerificando si tienen datos de Portes...")
for col in portes_cols[:3]:
    if col in ocupac_resultado.columns:
        no_nulos = ocupac_resultado[col].notna().sum()
        print(f"  {col}: {no_nulos}/{len(ocupac_resultado)} valores rellenados")

# Mostrar una fila de ejemplo
print("\n" + "="*80)
print("\nEjemplo de fila OCUPAC (primeras columnas):")
print(ocupac_resultado[['DESCRIPCIÓN', 'URGENCIA', 'FESTIVO', 'PESO (KG)', 'Volumen']].head(1).to_string())

================================================================================

Buscando 'OCUPAC' en df2 (Portes):
Encontrados 0 filas con 'OCUPAC' en df2
→ NO hay valores 'OCUPAC' en df2 (Portes)

================================================================================

Análisis de las filas OCUPAC en el resultado final:

Total de filas OCUPAC: 1467

Verificando si tienen datos de Portes...
  URGENCIA: 0/1467 valores rellenados
  FESTIVO: 0/1467 valores rellenados
  PROVINCIA DESTINO: 0/1467 valores rellenados

================================================================================

Ejemplo de fila OCUPAC (primeras columnas):
                                          DESCRIPCIÓN URGENCIA FESTIVO  PESO (KG)  Volumen
3520  OCUPACIÓNMEDIAALHAMBRA-IRISDELPALACIOAGOSTO2022      NaN     NaN        NaN      NaN

In [27]:
# Eliminar las filas que empiezan con OCUPAC
print("\n" + "="*80)
print("ELIMINANDO FILAS CON 'OCUPAC'")
print("="*80)

filas_antes = len(df_merged_limpio)
df_merged_limpio = df_merged_limpio[~df_merged_limpio['DESCRIPCIÓN'].str.startswith('OCUPAC', na=False)]
filas_despues = len(df_merged_limpio)
filas_eliminadas = filas_antes - filas_despues

print(f"\n✓ Filas antes: {filas_antes}")
print(f"✓ Filas eliminadas: {filas_eliminadas}")
print(f"✓ Filas después: {filas_despues}")
print(f"\n✓ Reducción: {(filas_eliminadas/filas_antes)*100:.2f}%")

print("\nDataframe después de eliminar OCUPAC:")
print(f"Forma final: {df_merged_limpio.shape}")
df_merged_limpio

================================================================================
ELIMINANDO FILAS CON 'OCUPAC'
================================================================================

✓ Filas antes: 23553
✓ Filas eliminadas: 1467
✓ Filas después: 22086

✓ Reducción: 6.23%

Dataframe después de eliminar OCUPAC:
Forma final: (22086, 23)

,ITEM,FECHA SERVICIO,CONCEPTO (DENOMINACIÓN EVENTO ASOCIADO),DESCRIPCIÓN,SOLICITANTE MAHOU,DPTO MAHOU,PALÉS IN,CAJAS IN,M3 IN,PALÉS OUT,...,CP,URGENCIA,FESTIVO,PROVINCIA DESTINO,TIEMPO RELOJ TRANSPORTE (HORAS),TIEMPO RELOJ CARGA Y DESCARGA (HORAS),Nº OPERARIOS (SIN CONTAR CHÓFER),PESO (KG),Volumen,CAJAS OUT
0,35372.0,NaT,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,32145.0,NaT,NaN,100000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,34186.0,2023-05-01,PORTE ENVIO PRODUCTO GANADOR PAULA LOPEZ JIMEN...,23,BEATRIZ DONOSO,MAHOU,NaN,NaN,NaN,NaN,...,30165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,34185.0,2023-04-03,PORTE ENVIO PRODUCTO GANADOR PAULA LOPEZ JIMEN...,24,BEATRIZ DONOSO,MAHOU,NaN,NaN,NaN,NaN,...,30165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,30235.0,2022-01-18,PORTE ENTREGA MOSTRADOR FITUR STAND ALCALA DE ...,24375,ALBA GARCIA,DCMC – Madrid,NaN,NaN,NaN,NaN,...,28042,NO,NO,Madrid,1.0,0.7,1.0,140.0,1.50,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23548,52637.0,2024-12-30,PORTE ENVIO URGENTE GPI,SGP202523811,GIULIA ARNOLS,RODAJE 5 ESTRELLAS,NaN,NaN,NaN,1.0,...,8711,NO,NO,Barcelona,0.0,0.0,0.0,180.0,0.40,NaN
23549,52633.0,2024-12-30,PORTE ENTREGA URGENTE SAICA,SGP202523812,GIULIA ARNOLS,RODAJE 5 ESTRELLAS,NaN,NaN,NaN,1.0,...,28108,NO,NO,Madrid,1.0,0.7,0.0,180.0,0.40,NaN
23550,52634.0,2024-12-30,PORTE ENTREGA URGENTE NEW BOX,SGP202523815,GIULIA ARNOLS,RODAJE 5 ESTRELLAS,NaN,NaN,NaN,1.0,...,28025,NO,NO,Madrid,1.0,0.7,1.0,180.0,0.40,NaN
23551,52640.0,2025-01-03,PORTE ENTREGA GRIFO ECESA,SGP202523817,BEATRIZ DONOSO,MAHOU,NaN,NaN,NaN,NaN,...,28906,NO,NO,Madrid,1.0,0.3,0.0,15.0,0.04,1.0
23552,52653.0,2025-03-18,EXPEDICION BOTELLERO BETO TORRES Y CARRERA,SGP202523821,JESUS MANUEL SAEZ,MAHOU GALICIA Y ASTURIAS,NaN,NaN,NaN,NaN,...,36416 - PONTEVEDRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
# Eliminar filas con FECHA SERVICIO en blanco
filas_antes = len(df_merged_limpio)
df_merged_limpio = df_merged_limpio[df_merged_limpio['FECHA SERVICIO'].notna()].copy()
filas_despues = len(df_merged_limpio)
print(f"Filas antes: {filas_antes}  |  Filas después: {filas_despues}  |  Eliminadas: {filas_antes - filas_despues}")

Filas antes: 22086  |  Filas después: 22043  |  Eliminadas: 43

In [33]:
# Guardar el dataframe actualizado con la DESCRIPCIÓN normalizada, volumen, columnas limpias y sin OCUPAC
df_merged_limpio.to_excel(r'c:\Users\rdiezl\Desktop\proyecto\planificacion\Datos\Informacion_albaranaes.xlsx', index=False)

✓ Archivo guardado correctamente.
  - Total de filas: 22043
  - Filas sin OCUPAC: Sí
  - Total de columnas: 23